Repository powsybl/powsybl-open-rao, pull requests merged in 2020-08, with the labels that each got.

#296 Better variants handling
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoUnitTest.java
  ra-optimisation/search-tree-rao/src/test/resources/small-crac-with-network-actions.json
Labels: PR: waiting-for-correction, cleaning

#303 modify EICode
  util/src/main/java/com/farao_community/farao/util/EICode.java
Labels: PR: WIP

#304 Create network aliases creation class inside FARAO to adapt the need
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/NetworkElement.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUcteAliasesCreation.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUcteAliasesCreationTest.java
  ra-optimisation/rao-commons/src/test/resources/TestCase12Nodes_withXnodes.uct
Labels: PR: waiting-for-review

#315 Remove powsybl balances adjustment dependency
  flowbased-computation/flowbased-computation-impl/pom.xml
  loopflow-computation/pom.xml
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/CountryNetPositionComputation.java
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/CountryNetPositionComputationTest.java
  loopflow-computation/src/test/resources/TestCaseDangling.xiidm
  loopflow-computation/src/test/resources/TestCaseHvdc.xiidm
  loopflow-computation/src/test/resources/testCase.xiidm
  pom.xml
Labels: PR: ready-to-be-merged
