Repository powsybl/powsybl-open-rao, pull requests merged in 2020-07, with the labels that each got.

#286 Modify logs for clarity on range actions and costs
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java
Labels: PR: ready-to-be-merged

#291 Fix cnec getMin/MaxThreshold behaviour
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecAdderTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecTest.java
Labels: PR: waiting-for-review

#288 Handle MNECs in optimization
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoUtil.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoUtilTest.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/MinMarginEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/MinMarginObjectiveFunction.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/MnecViolationCostEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/ObjectiveFunctionEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblem.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizer.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerWithLoopFlows.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MinMarginEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MinMarginObjectiveFunctionTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MnecViolationCostEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataManagerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerTest.java
  ra-optimisation/rao-commons/src/test/resources/small-crac.json
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
Labels: PR: waiting-for-review

#295 Cnec get FRM and minor udpate on build loopflow
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Cnec.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
Labels: PR: waiting-for-review

#302 PowSyBl upgrade: core 3.5.0 and rte-core 2.12.0
  flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParameters.json
  flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersError.json
  flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersIncomplete.json
  flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersWithExtension.json
  flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParameters.json
  flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersError.json
  flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersIncomplete.json
  flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersWithExtension.json
  pom.xml
  ra-optimisation/closed-optimisation-rao/src/test/resources/json/validParameters.json
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParameters.json
  ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersError.json
  ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersIncomplete.json
  ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersWithExtension.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersSet.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersError.json
  ra-optimisation/search-tree-rao/src/test/resources/parameters.json
Labels: PR: waiting-for-review, dependencies

#300 Add timestamp filter to crac importer
  data/crac-io/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracImporter.java
  data/crac-io/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracImporters.java
  data/crac-io/crac-io-api/src/test/java/com/farao_community/farao/data/crac_io_api/CracExportersImportersTest.java
  data/crac-io/crac-io-api/src/test/java/com/farao_community/farao/data/crac_io_api/CracImporterMock.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/JsonImport.java
Labels: PR: ready-to-be-merged, enhancement

#301 Loopflow threshold with unit
  data/crac/crac-loopflow-extension/pom.xml
  data/crac/crac-loopflow-extension/src/main/java/com/farao_community/farao/data/crac_loopflow_extension/CnecLoopFlowExtension.java
  data/crac/crac-loopflow-extension/src/main/java/com/farao_community/farao/data/crac_loopflow_extension/JsonCnecLoopFlowExtensionSerializer.java
  data/crac/crac-loopflow-extension/src/test/java/com/farao_community/farao/data/crac_loopflow_extension/CnecLoopFlowExtensionTest.java
  data/crac/crac-loopflow-extension/src/test/java/com/farao_community/farao/data/crac_loopflow_extension/CracLoopFlowExtensionTest.java
  data/crac/crac-loopflow-extension/src/test/java/com/farao_community/farao/data/crac_loopflow_extension/JsonCnecLoopFlowExtensionImportExportTest.java
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/LoopFlowComputationService.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoDataManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataManagerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFillerTest.java
Labels: PR: ready-to-be-merged, enhancement
