Repository powsybl/powsybl-open-rao, pull requests merged in 2020-09, with the labels that each got.

#317 Change OnContingency usage rule to OnState usage rule
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/CracImplJsonModule.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/JsonSerializationNames.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/UsageRuleDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/usage_rule/OnContingencySerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/usage_rule/OnStateSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/usage_rule/AbstractUsageRule.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/usage_rule/OnContingency.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/usage_rule/OnState.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/CracImportExportTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/usage_rule/OnContingencyTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/usage_rule/OnStateTest.java
Labels: PR: waiting-for-review

#322 Fix checkstyle failure during install.sh
  checkstyle-suppressions.xml
Labels: PR: waiting-for-review, bug

#325 Curative optimization: step 1
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/UsageMethod.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/UsageRule.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/AbstractRemedialAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/usage_rule/AbstractUsageRule.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/usage_rule/FreeToUse.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/usage_rule/OnConstraint.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/usage_rule/OnState.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/utils/CommonCracCreation.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoInput.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/MinMarginEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/MnecViolationCostEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoDataManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/SystematicSensitivityComputation.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFiller.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MinMarginEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MinMarginObjectiveFunctionTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MnecViolationCostEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataManagerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/SystematicSensitivityComputationTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearOptimizerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/AbstractFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoUnitTest.java
Labels: PR: waiting-for-review

#321 Upgrade OR-Tools and use FARAO released version 7.8.7959
  pom.xml
  ra-optimisation/closed-optimisation-rao/pom.xml
  ra-optimisation/linear-rao/pom.xml
  ra-optimisation/ra-optimisation-api/pom.xml
  ra-optimisation/rao-commons/pom.xml
Labels: PR: WIP, dependencies

#326 Refprog in lf
  data/crac-io/crac-io-api/pom.xml
  data/crac/crac-loopflow-extension/src/main/java/com/farao_community/farao/data/crac_loopflow_extension/CracLoopFlowExtension.java
  data/crac/crac-loopflow-extension/src/test/java/com/farao_community/farao/data/crac_loopflow_extension/CracLoopFlowExtensionTest.java
  data/refprog/reference-program/pom.xml
  data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/CountryNetPositionComputation.java
  data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgram.java
  data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramBuilder.java
  data/refprog/reference-program/src/test/java/com/farao_community/farao/data/refprog/reference_program/CountryNetPositionComputationTest.java
  data/refprog/reference-program/src/test/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramBuilderTest.java
  data/refprog/reference-program/src/test/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramTest.java
  data/refprog/reference-program/src/test/resources/TestCaseDangling.xiidm
  data/refprog/reference-program/src/test/resources/TestCaseHvdc.xiidm
  data/refprog/reference-program/src/test/resources/testCase.xiidm
  data/refprog/refprog-xml-importer/src/main/java/com/farao_community/farao/data/refprog/refprog_xml_importer/RefProgImporter.java
  data/refprog/refprog-xml-importer/src/test/java/com/farao_community/farao/data/refprog/refprog_xml_importer/RefProgImporterTest.java
  loopflow-computation/pom.xml
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoInput.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/LoopFlowComputationService.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/LoopFlowComputationServiceTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataManagerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/AbstractFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
Labels: PR: ready-to-be-merged

#327 fix import of CORE RefProg
  data/refprog/refprog-xml-importer/src/main/java/com/farao_community/farao/data/refprog/refprog_xml_importer/RefProgImporter.java
  data/refprog/refprog-xml-importer/src/main/resources/xjb/binding.xjb
  data/refprog/refprog-xml-importer/src/main/resources/xsd/etso-code-lists.xsd
  data/refprog/refprog-xml-importer/src/main/resources/xsd/etso-core-cmpts.xsd
  data/refprog/refprog-xml-importer/src/main/resources/xsd/publication-document-v2r0.xsd
  data/refprog/refprog-xml-importer/src/main/resources/xsd/refprog.xsd
  data/refprog/refprog-xml-importer/src/test/resources/large_refProg.xml
  data/refprog/refprog-xml-importer/src/test/resources/refProg_12nodes.xml
  data/refprog/refprog-xml-importer/src/test/resources/refProg_noInterval.xml
  data/refprog/refprog-xml-importer/src/test/resources/wrong_refProg.xml
Labels: PR: waiting-for-review

#328 Fix linear optim
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFiller.java
Labels: PR: waiting-for-review

#331 modified checkSensi to use provider cnecs, added loadflowProvider
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/AbstractSimpleSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/CnecSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/LoadflowProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/MultipleSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/RangeActionSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityInterface.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityService.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/LoadflowProviderTest.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/RangeActionSensitivityProviderTest.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityInterfaceTest.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityServiceTest.java
Labels: PR: waiting-for-review, cleaning

#330 Use new sensi module for ra
  ra-optimisation/linear-rao/pom.xml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/rao-commons/pom.xml
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CostEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/MinMarginEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/MnecViolationCostEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoDataManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/SystematicSensitivityComputation.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizer.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerWithLoopFlows.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MinMarginEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MinMarginObjectiveFunctionTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MnecViolationCostEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/SystematicSensitivityComputationTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearOptimizerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/AbstractFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoUnitTest.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/AbstractSimpleSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/RangeActionSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityInterface.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/MultipleSensitivityProviderTest.java
  util/src/main/java/com/farao_community/farao/util/CracContingenciesProvider.java
  util/src/main/java/com/farao_community/farao/util/CracFactorsProvider.java
  util/src/main/java/com/farao_community/farao/util/SensitivityComputationException.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResult.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java
  util/src/test/java/com/farao_community/farao/util/CracContingenciesProviderTest.java
  util/src/test/java/com/farao_community/farao/util/CracFactorsProviderTest.java
  util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResultTest.java
  util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java
Labels: PR: waiting-for-review, cleaning

#324 Refactoring sensitivity computation
  distribution/pom.xml
  pom.xml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/rao-commons/pom.xml
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CostEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/MinMarginEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/MnecViolationCostEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoDataManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/SystematicSensitivityComputation.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizer.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerWithLoopFlows.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MinMarginEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MinMarginObjectiveFunctionTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MnecViolationCostEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearOptimizerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/AbstractFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoUnitTest.java
  sensitivity-computation/pom.xml
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/AbstractSimpleSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/CnecSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/LoadflowProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/MultipleSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/PtdfSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/RangeActionSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/SensitivityComputationException.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityInterface.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityResult.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityService.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/LoadflowProviderTest.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/MultipleSensitivityProviderTest.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/PtdfSensitivityProviderTest.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/RangeActionSensitivityProviderTest.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityInterfaceTest.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityResultTest.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityServiceTest.java
  sensitivity-computation/src/test/resources/DefaultSensitivityComputationParameters.json
  sensitivity-computation/src/test/resources/FallbackSystematicSensitivityComputationParameters.json
  util/src/main/java/com/farao_community/farao/util/CracFactorsProvider.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java
  util/src/test/java/com/farao_community/farao/util/CracContingenciesProviderTest.java
  util/src/test/java/com/farao_community/farao/util/CracFactorsProviderTest.java
  util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java
Labels: PR: ready-to-be-merged

#335 get flow on branch which are not in the primary connex component
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecTest.java
  data/crac/crac-impl/src/test/resources/TestCase15Nodes_2_components.uct
Labels: PR: ready-to-be-merged
