Repository powsybl/powsybl-open-rao, pull requests merged in 2020-06, with the labels that each got.

#256 Max min margin in AMPERE
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/CracResult.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/CracResultTest.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/JsonResultTest.java
  data/crac/crac-result-extensions/src/test/resources/small-crac-with-result-extensions.json
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearOptimisationEngine.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngine.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/LinearRaoConfigurationUtil.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/LinearRaoParameters.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxMinMarginFiller.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngineTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/mock/RaoRunnerMock.java
  util/src/main/java/com/farao_community/farao/util/CracFactorsProvider.java
Labels: PR: ready-to-be-merged

#259 CNE export part 1
  data/crac-io/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracExporter.java
  data/crac-io/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracExporters.java
  data/crac-io/crac-io-api/src/test/java/com/farao_community/farao/data/crac_io_api/CracExporterMock.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/JsonExport.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Crac.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/DeserializerNames.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/SimpleCracDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCracSerializer.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/CracImportExportTest.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/RangeActionResult.java
Labels: PR: ready-to-be-merged

#263 Move EICode and make it reversible
  data/glsk/glsk-file/pom.xml
  data/glsk/glsk-file/src/main/java/com/farao_community/farao/data/glsk/import_/actors/GlskPointLinearGlskConverter.java
  data/glsk/glsk-file/src/main/java/com/farao_community/farao/data/glsk/import_/actors/GlskPointScalableConverter.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/farao_community/farao/flowbased_computation/csv_exporter/FlowBasedCountry.java
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
  util/src/main/java/com/farao_community/farao/util/EICode.java
  util/src/test/java/com/farao_community/farao/util/EICodeTest.java
Labels: PR: waiting-for-review

#265 Cne header
  data/crac-io/crac-io-cne/pom.xml
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/Cne.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneClassCreator.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneConstants.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneExport.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneHelper.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneUtil.java
  data/crac-io/crac-io-cne/src/main/resources/xjb/binding.xjb
  data/crac-io/crac-io-cne/src/main/resources/xsd/iec62325-451-n-cne_v2_4.xsd
  data/crac-io/crac-io-cne/src/main/resources/xsd/urn-entsoe-eu-local-extension-types.xsd
  data/crac-io/crac-io-cne/src/main/resources/xsd/urn-entsoe-eu-wgedi-codelists.xsd
  data/crac-io/crac-io-cne/src/test/java/com/farao_community/farao/data/crac_io_cne/CneExportTest.java
  data/crac-io/crac-io-cne/src/test/java/com/farao_community/farao/data/crac_io_cne/CneGenerationTest.java
  data/crac-io/crac-io-cne/src/test/resources/US2-3-case1-standard.uct
  data/crac-io/crac-io-cne/src/test/resources/US2-3-crac1-standard.json
  data/crac-io/crac-io-cne/src/test/resources/US3-2-pst-direct.json
  data/crac-io/pom.xml
  distribution/pom.xml
  pom.xml
Labels: PR: waiting-for-review

#252 Loopflow PTDF approximation
  data/crac/crac-loopflow-extension/src/main/java/com/farao_community/farao/data/crac_loopflow_extension/CnecLoopFlowExtension.java
  data/crac/crac-loopflow-extension/src/test/java/com/farao_community/farao/data/crac_loopflow_extension/CracLoopFlowExtensionTest.java
  distribution/src/main/resources/config.yml
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngine.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersWithFallback.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoUnitTest.java
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: waiting-for-review

#271 CNE export remedial actions
  data/crac-io/crac-io-cne/pom.xml
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/Cne.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneClassCreator.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneHelper.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneRemedialActionsCreator.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneUtil.java
  data/crac-io/crac-io-cne/src/test/java/com/farao_community/farao/data/crac_io_cne/CneGenerationTest.java
  data/crac-io/crac-io-cne/src/test/resources/US2-3-crac1-standard.json
  data/crac-io/crac-io-cne/src/test/resources/US3-2-pst-direct.json
Labels: PR: waiting-for-review

#269 CNE Export cnecs
  data/crac-io/crac-io-cne/pom.xml
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/Cne.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneClassCreator.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneCnecsCreator.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneConstants.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneHelper.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneRemedialActionsCreator.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneUtil.java
  data/crac-io/crac-io-cne/src/main/resources/xsd/urn-entsoe-eu-local-extension-types.xsd
  data/crac-io/crac-io-cne/src/main/resources/xsd/urn-entsoe-eu-wgedi-codelists.xsd
  data/crac-io/crac-io-cne/src/test/java/com/farao_community/farao/data/crac_io_cne/CneExportTest.java
  data/crac-io/crac-io-cne/src/test/java/com/farao_community/farao/data/crac_io_cne/CneGenerationTest.java
  data/crac-io/crac-io-cne/src/test/resources/US2-3-crac1-standard.json
  data/crac-io/crac-io-cne/src/test/resources/US3-2-pst-direct.json
Labels: PR: waiting-for-review

#262 Loopflow LoopflowConstraintAdjustmentCoefficient
  distribution/src/main/resources/config.yml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersWithFallback.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: ready-to-be-merged

#274 Update Google Guava
  pom.xml
Labels: PR: ready-to-be-merged, dependencies

#272 management of FRM during computation
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/CnecAdder.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnecAdder.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbsoluteFlowThreshold.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbstractFlowThreshold.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/AbstractThreshold.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/RelativeFlowThreshold.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/VoltageThreshold.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecAdderTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/CracImportExportTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/threshold/AbsoluteFlowThresholdTest.java
Labels: PR: waiting-for-review

#276 CNE Bug fixing
  checkstyle-suppressions.xml
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneRemedialActionsCreator.java
  pom.xml
Labels: PR: waiting-for-review, bug

#270 Loopflow violation cost
  distribution/src/main/resources/config.yml
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngine.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/LinearRaoConfigurationUtil.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/LinearRaoProblem.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearOptimisationEngineTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngineTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/LinearRaoProblemTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersWithFallback.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: waiting-for-review

#281 Adapt Crac api to MNEC management
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Cnec.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/CnecAdder.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnecAdder.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/CnecDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/DeserializerNames.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCnecSerializer.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SimpleCnecAdderTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/CracImportExportTest.java
Labels: PR: ready-to-be-merged

#283 Reuse tags in serialization
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/JsonSerializationNames.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/CnecDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/ContingencyDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/NetworkActionDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/RangeActionDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/SimpleCracDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/StateDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/UsageRuleDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/AbstractRemedialActionSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/ComplexContingencySerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCnecSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCracSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleStateSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/ComplexNetworkActionSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/PstSetPointSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/TopologySerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/range_action/RangeActionSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/usage_rule/OnConstraintSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/usage_rule/OnContingencySerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/usage_rule/UsageRuleSerializer.java
Labels: PR: waiting-for-review

#285 Filter out CNECs that are neither optimized nor monitored before RAO
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoInput.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoInputTest.java
Labels: PR: waiting-for-review
