Repository powsybl/powsybl-open-rao, pull requests merged in 2020-04, with the labels that each got.

#186 new RaoResult to replace RaoComputationResult
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/NetworkActionDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/ComplexNetworkActionSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/NetworkActionSerializer.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/ResultVariantManager.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/ResultVariantManagerTest.java
  ra-optimisation/linear-rao/pom.xml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/AbstractPostProcessor.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/JsonLinearRaoResult.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoModeller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoResult.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/post_processors/PstTapPostProcessor.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/post_processors/RaoResultPostProcessor.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/JsonLinearRaoResultTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoModellerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoResultTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/post_processors/RaoResultPostProcessorTest.java
  ra-optimisation/rao-api/pom.xml
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/Rao.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoProvider.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoResult.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoTool.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoResultTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/rao_mock/AnotherRaoProviderMock.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/rao_mock/RaoProviderMock.java
  ra-optimisation/search-tree-rao/pom.xml
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoResultExporter.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoResultImporter.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoResultExporter.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoResultExporters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoResultImporter.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoResultImporters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/JsonSearchTreeRaoResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoUnitTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/mock/LinearRaoMock.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/mock/RaoRunnerMock.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/process/search_tree/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/process/search_tree/TreeTest.java
Labels: PR: ready-to-be-merged, enhancement

#216 Remove static loading of jniortools system library from RAOs and put it in singleton service
  ra-optimisation/closed-optimisation-rao/src/main/java/com/farao_community/farao/closed_optimisation_rao/ClosedOptimisationRao.java
  ra-optimisation/closed-optimisation-rao/src/test/java/com/farao_community/farao/closed_optimisation_rao/ClosedOptimisationRaoTest.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  util/src/main/java/com/farao_community/farao/util/NativeLibraryLoader.java
  util/src/test/java/com/farao_community/farao/util/NativeLibraryLoaderTest.java
Labels: PR: ready-to-be-merged, enhancement

#217 Fallback sensi config
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/JsonLinearRaoParameters.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/LinearRaoConfigLoader.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/LinearRaoParameters.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/config/JsonLinearRaoParametersTest.java
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersWithFallback.json
  util/src/main/java/com/farao_community/farao/util/SensitivityComputationException.java
Labels: PR: waiting-for-correction

#219 Fix project bugs and vulnerabilities
  data/crac-file/crac-file-xlsx-api/src/main/java/com/farao_community/farao/data/crac_file/xlsx/handler/EntityHandler.java
  data/glsk/glsk-file/src/main/java/com/farao_community/farao/data/glsk/import_/GlskDocument.java
  data/glsk/glsk-file/src/main/java/com/farao_community/farao/data/glsk/import_/UcteGlskDocument.java
Labels: PR: waiting-for-review, cleaning

#220 Allow thresholds above 100 percents
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/RelativeFlowThreshold.java
Labels: PR: ready-to-be-merged

#218 Export of the sensi params choice
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoResult.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/json/JsonLinearRaoResult.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/json/JsonLinearRaoResultTest.java
  ra-optimisation/linear-rao/src/test/resources/RaoResultDefaultSensi.json
  ra-optimisation/linear-rao/src/test/resources/RaoResultFallbackSensi.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoResult.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/JsonRaoResult.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoResultDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoResultJsonModule.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoResultSerializer.java
Labels: PR: ready-to-be-merged

#224 Define new parameters in Search Tree configuration
  distribution/src/main/resources/config.yml
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/config/JsonSearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/config/SearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/config/SearchTreeRaoParametersConfigLoader.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/config/JsonSearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: ready-to-be-merged

#221 Remove CRAC dependency to Sensitivity API
  data/crac/crac-api/pom.xml
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/RangeAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/AbstractElementaryRangeAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/AlignedRangeAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/Countertrading.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/Redispatching.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/utils/CommonCracCreation.java
  ra-optimisation/linear-rao/pom.xml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoData.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/CoreProblemFiller.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/fillers/CoreProblemFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/linear-rao/src/test/resources/small-sensi-results-1.json
  ra-optimisation/linear-rao/src/test/resources/small-sensi-results-2.json
  ra-optimisation/rao-api/pom.xml
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/Rao.java
  util/src/main/java/com/farao_community/farao/util/CracFactorsProvider.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResult.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java
  util/src/test/java/com/farao_community/farao/util/CracFactorsProviderTest.java
  util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResultTest.java
  util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java
Labels: PR: ready-to-be-merged

#227 Harmonize logging framework usage
  commons/pom.xml
  commons/src/test/resources/logback-test.xml
  data/crac-file/crac-file-api/pom.xml
  data/crac-file/crac-file-api/src/test/resources/logback-test.xml
  data/crac-file/crac-file-xlsx-api/pom.xml
  data/crac-file/crac-file-xlsx-api/src/test/resources/logback-test.xml
  data/crac-file/crac-merging/pom.xml
  data/crac-file/crac-merging/src/test/resources/logback-test.xml
  data/crac-io/crac-io-api/pom.xml
  data/crac-io/crac-io-api/src/test/resources/logback-test.xml
  data/crac-io/crac-io-json/pom.xml
  data/crac-io/crac-io-json/src/test/resources/logback-test.xml
  data/crac/crac-api/pom.xml
  data/crac/crac-api/src/test/resources/logback-test.xml
  data/crac/crac-impl/pom.xml
  data/crac/crac-impl/src/test/resources/logback-test.xml
  data/crac/crac-loopflow-extension/pom.xml
  data/crac/crac-loopflow-extension/src/test/resources/logback-test.xml
  data/crac/crac-result-extensions/pom.xml
  data/crac/crac-result-extensions/src/test/resources/logback-test.xml
  data/flow-decomposition-results/flow-decomposition-results-api/pom.xml
  data/flow-decomposition-results/flow-decomposition-results-api/src/test/resources/logback-test.xml
  data/flow-decomposition-results/flow-decomposition-results-xlsx-converter/pom.xml
  data/flow-decomposition-results/flow-decomposition-results-xlsx-converter/src/test/resources/logback-test.xml
  data/flowbased-domain/flowbased-domain-api/pom.xml
  data/flowbased-domain/flowbased-domain-api/src/test/resources/logback-test.xml
  data/glsk/glsk-file/pom.xml
  data/glsk/glsk-file/src/test/resources/logback-test.xml
  data/glsk/glsk-quality-check/pom.xml
  data/glsk/glsk-quality-check/src/test/resources/logback-test.xml
  distribution/src/main/resources/logback.xml
  flow-decomposition/flow-decomposition-api/pom.xml
  flow-decomposition/flow-decomposition-api/src/test/resources/logback-test.xml
  flow-decomposition/full-line-decomposition/pom.xml
  flow-decomposition/full-line-decomposition/src/test/resources/logback-test.xml
  flowbased-computation/flowbased-computation-api/pom.xml
  flowbased-computation/flowbased-computation-api/src/test/resources/logback-test.xml
  flowbased-computation/flowbased-computation-impl/pom.xml
  flowbased-computation/flowbased-computation-impl/src/test/resources/logback-test.xml
  pom.xml
  ra-optimisation/closed-optimisation-rao/pom.xml
  ra-optimisation/closed-optimisation-rao/src/test/java/com/farao_community/farao/closed_optimisation_rao/groovy/TestCracGenerator.groovy
  ra-optimisation/closed-optimisation-rao/src/test/resources/logback-test.xml
  ra-optimisation/linear-rao/pom.xml
  ra-optimisation/ra-optimisation-api/pom.xml
  ra-optimisation/rao-api/pom.xml
  ra-optimisation/search-tree-rao/pom.xml
  util/pom.xml
  util/src/test/resources/logback-test.xml
Labels: PR: waiting-for-review, cleaning

#228 Filtering of small sensitivities in LinearRao
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/AbstractProblemFiller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoModeller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/JsonLinearRaoParameters.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/LinearRaoConfigLoader.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/LinearRaoParameters.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/CoreProblemFiller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/MaxLoopFlowFiller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/MaxMinMarginFiller.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoModellerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/config/JsonLinearRaoParametersTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/config/LinearRaoConfigLoaderTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/config/LinearRaoParametersTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/fillers/AbstractFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/fillers/CoreProblemFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/mocks/MPConstraintMock.java
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersWithFallback.json
Labels: PR: ready-to-be-merged

#222 Refactor linear rao
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/ResultVariantManager.java
  ra-optimisation/linear-rao/pom.xml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/AbstractPostProcessor.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/AbstractProblemFiller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearOptimisationEngine.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoData.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoModeller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoResult.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngine.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/LinearOptimisationException.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/LinearRaoProblem.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/CoreProblemFiller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxMinMarginFiller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/ProblemFiller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/post_processors/RaoResultPostProcessor.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearOptimisationEngineTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoDataTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoModellerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoResultTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngineTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/LinearRaoProblemTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/AbstractFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/CoreProblemFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/post_processors/RaoResultPostProcessorTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
  util/src/main/java/com/farao_community/farao/util/SensitivityComputationException.java
Labels: PR: waiting-for-correction
