Repository powsybl/powsybl-open-rao, pull requests merged in 2020-05, with the labels that each got.

#232 Update PowSyBl dependencies version
  distribution/src/main/resources/config.yml
  flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParameters.json
  flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersError.json
  flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersIncomplete.json
  flow-decomposition/flow-decomposition-api/src/test/resources/FlowDecompositionParametersWithExtension.json
  flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParameters.json
  flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersError.json
  flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersIncomplete.json
  flow-decomposition/flow-decomposition-api/src/test/resources/SensitivityComputationParametersWithExtension.json
  pom.xml
  ra-optimisation/closed-optimisation-rao/src/test/resources/json/validParameters.json
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersError.json
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersWithFallback.json
  ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParameters.json
  ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersError.json
  ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersIncomplete.json
  ra-optimisation/ra-optimisation-api/src/test/resources/RaoComputationParametersWithExtension.json
Labels: PR: waiting-for-review, dependencies

#231 Multithreading leaf evaluations
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/ResultVariantManager.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/process/search_tree/LeafTest.java
Labels: PR: waiting-for-review

#238 Handle frm
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/CnecDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/DeserializerNames.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCnecSerializer.java
Labels: PR: waiting-for-review

#237 Single out loopflow from flowbased
  distribution/pom.xml
  loopflow-computation/pom.xml
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/ExampleGenerator.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
  pom.xml
  ra-optimisation/linear-rao/pom.xml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/search-tree-rao/pom.xml
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java
Labels: PR: ready-to-be-merged

#236 Initial version of systematic sensitivity analysis migration
  commons/pom.xml
  commons/src/main/java/com/farao_community/farao/commons/RandomizedString.java
  commons/src/test/java/com/farao_community/farao/commons/RandomizedStringTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/utils/NetworkImportsUtil.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/ResultVariantManager.java
  flowbased-computation/flowbased-computation-impl/src/main/java/com/farao_community/farao/flowbased_computation/impl/FlowBasedComputationImpl.java
  flowbased-computation/flowbased-computation-impl/src/test/java/com/farao_community/farao/flowbased_computation/impl/ExampleGenerator.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/ExampleGenerator.java
  pom.xml
  ra-optimisation/closed-optimisation-rao/src/test/java/com/farao_community/farao/closed_optimisation_rao/mocks/MockSensitivityComputationFactory.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoData.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngine.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearOptimisationEngineTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngineTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/AbstractFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/CoreProblemFillerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
  util/pom.xml
  util/src/main/java/com/farao_community/farao/util/CracContingenciesProvider.java
  util/src/main/java/com/farao_community/farao/util/CracFactorsProvider.java
  util/src/main/java/com/farao_community/farao/util/FaraoNetworkPool.java
  util/src/main/java/com/farao_community/farao/util/FaraoVariantsPool.java
  util/src/main/java/com/farao_community/farao/util/SensitivityComputationService.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResult.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java
  util/src/test/java/com/farao_community/farao/util/CracContingenciesProviderTest.java
  util/src/test/java/com/farao_community/farao/util/CracFactorsProviderTest.java
  util/src/test/java/com/farao_community/farao/util/FaraoNetworkPoolTest.java
  util/src/test/java/com/farao_community/farao/util/SensitivityComputationServiceTest.java
  util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResultTest.java
  util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java
Labels: PR: waiting-for-info-reviewer, enhancement

#241 Upgrade PowSyBl RTE CORE
  pom.xml
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResult.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java
  util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResultTest.java
  util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java
Labels: PR: waiting-for-review, dependencies

#247 Fix root evaluation not switching back to initial variant
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
Labels: PR: waiting-for-review

#242 Add pst penalty cost parameter
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/JsonLinearRaoParameters.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/LinearRaoConfigLoader.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/config/LinearRaoParameters.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxMinMarginFiller.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/config/JsonLinearRaoParametersTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/config/LinearRaoConfigLoaderTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/config/LinearRaoParametersTest.java
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParametersWithFallback.json
Labels: PR: ready-to-be-merged

#249 Improvements after real-size data tests
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearOptimisationEngine.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/config/JsonSearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/config/SearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/config/SearchTreeRaoParametersConfigLoader.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Tree.java
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
  util/src/main/java/com/farao_community/farao/util/CracFactorsProvider.java
  util/src/main/java/com/farao_community/farao/util/SensitivityComputationService.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResult.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java
  util/src/test/java/com/farao_community/farao/util/CracFactorsProviderTest.java
Labels: PR: waiting-for-review

#255 Loopflow check non null CnecLoopflowExtension
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngine.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFiller.java
Labels: PR: ready-to-be-merged

#250 Prepare for linear rao loopflow regression test
  data/crac/crac-loopflow-extension/src/main/java/com/farao_community/farao/data/crac_loopflow_extension/CracLoopFlowExtension.java
  data/crac/crac-loopflow-extension/src/test/java/com/farao_community/farao/data/crac_loopflow_extension/CracLoopFlowExtensionTest.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/CnecResult.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/CnecResultTest.java
  data/glsk/glsk-file/src/main/java/com/farao_community/farao/data/glsk/import_/UcteGlskDocument.java
  data/glsk/glsk-file/src/test/java/com/farao_community/farao/data/glsk/import_/UcteGlskDocumentImporterTest.java
  loopflow-computation/pom.xml
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
  loopflow-computation/src/test/resources/TestCase12Nodes.uct
  loopflow-computation/src/test/resources/glsk_lots_of_lf_12nodes.xml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearOptimisationEngine.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngine.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/SystematicAnalysisEngineTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java
Labels: PR: ready-to-be-merged
