Repository powsybl/powsybl-open-rao, pull requests merged in 2020-10, with the labels that each got.

#336 Adapt loop-flow computation to new common sensi module
  loopflow-computation/pom.xml
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowResult.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/ExampleGenerator.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowResultTest.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoParametersTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/LoopFlowComputationService.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/LoopFlowUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/MinMarginObjectiveFunction.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoDataManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblem.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizer.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerWithLoopFlows.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/CostEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/LoopFlowViolationCostEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginObjectiveFunction.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MnecViolationCostEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/ObjectiveFunctionEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/SensitivityFallbackOvercostEvaluator.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/ExampleGenerator.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysisTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/LoopFlowUtilTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/MinMarginObjectiveFunctionTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataManagerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblemTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/LoopFlowViolationCostEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginObjectiveFunctionTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MnecViolationCostEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/SensitivityFallbackOvercostEvaluatorTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoUnitTest.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/PtdfSensitivityProvider.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityInterface.java
  sensitivity-computation/src/main/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityResult.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/MultipleSensitivityProviderTest.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/PtdfSensitivityProviderTest.java
  sensitivity-computation/src/test/java/com/farao_community/farao/sensitivity_computation/SystematicSensitivityResultTest.java
  sensitivity-computation/src/test/resources/glsk_proportional_12nodes.xml
Labels: PR: ready-to-be-merged

#348 Add runtime dependency on log4j-over-slf4j
  distribution/pom.xml
  pom.xml
Labels: PR: waiting-for-review

#347 Fix issue in javadoc creation
  pom.xml
Labels: PR: waiting-for-correction

#351 Fix CNE export
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneUtil.java
  data/crac-io/crac-io-cne/src/test/java/com/farao_community/farao/data/crac_io_cne/CneGenerationTest.java
Labels: PR: waiting-for-review

#332 filter contingencies on invalid network elements
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoInputHelper.java
Labels: PR: waiting-for-review

#353 Handle contingencies on Dangling lines
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/ComplexContingency.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/AbstractSimpleSensitivityProvider.java
Labels: PR: waiting-for-review

#354 Add GLSK factors to flowbased results
  data/flowbased-domain/src/main/java/com/farao_community/farao/data/flowbased_domain/DataDomain.java
  data/flowbased-domain/src/main/java/com/farao_community/farao/data/flowbased_domain/DataGlskFactors.java
  data/flowbased-domain/src/test/java/com/farao_community/farao/data/flowbased_domain/json/JsonFlowbasedDomainTest.java
  data/flowbased-domain/src/test/resources/dataDomain.json
  flowbased-computation/flowbased-computation-api/src/test/java/com/farao_community/farao/flowbased_computation/json/JsonFlowbasedComputationResultTest.java
  flowbased-computation/flowbased-computation-api/src/test/resources/FlowbasedComputationResult.json
  flowbased-computation/flowbased-computation-impl/src/main/java/com/farao_community/farao/flowbased_computation/impl/FlowbasedComputationImpl.java
Labels: PR: waiting-for-review

#355 Fix wrong dependency on iidm-scripting in distribution module
  distribution/pom.xml
Labels: PR: waiting-for-review, bug

#349 loopflow filtering per countries
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersSet.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithFallback.json
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/LoopFlowUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoDataManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/LoopFlowViolationCostEvaluator.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/AbstractFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/LoopFlowViolationCostEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MnecViolationCostEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/resources/RaoPtdfParameters.json
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: waiting-for-correction
