Repository powsybl/powsybl-open-rao, pull requests merged in 2020-03, with the labels that each got.

#197 Update Hades2 version
  pom.xml
Labels: PR: waiting-for-review, dependencies

#193 Add dc-mode and ac-to-dc-fallback parameters to SearchTreeRao
  distribution/src/main/resources/config.yml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java
  util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java
Labels: PR: waiting-for-review, question

#183 Adapt linear rao to result extensions
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Cnec.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Crac.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/NetworkAction.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/PstRange.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/RangeAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCnec.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/CracImplJsonModule.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/AbstractRemedialActionSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/NetworkActionSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/range_action/ElementaryRangeActionSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/range_action/PstWithRangeSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/range_action/RangeActionSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/AbstractElementaryNetworkAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/AbstractNetworkAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/AbstractSetpointElementaryNetworkAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/ComplexNetworkAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/HvdcSetpoint.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/InjectionSetpoint.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/PstSetpoint.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/Topology.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/AbstractElementaryRangeAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/AbstractRangeAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/AlignedRangeAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/Countertrading.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/HvdcRange.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/InjectionRange.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstWithRange.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/Redispatching.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/NetworkActionResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/PstRangeResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/RangeActionResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/ResultVariantManager.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/ResultVariantManagerTest.java
  ra-optimisation/linear-rao/pom.xml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/AbstractPostProcessor.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoModeller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/post_processors/PstTapPostProcessor.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/post_processors/RaoResultPostProcessor.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoModellerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/post_processors/RaoResultPostProcessorTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisResult.java
  util/src/main/java/com/farao_community/farao/util/SystematicSensitivityAnalysisService.java
  util/src/test/java/com/farao_community/farao/util/SystematicSensitivityAnalysisServiceTest.java
Labels: PR: waiting-for-review, enhancement

#195 Crac extension io json
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/ExtensionsHandler.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/CracImplJsonModule.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/CnecDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/SimpleCracDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCnecSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleCracSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/SimpleStateSerializer.java
  data/crac/crac-result-extensions/pom.xml
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/AbstractJsonResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/AbstractResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/CnecResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/CracResult.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/CracResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/JsonCnecResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/JsonCracResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/JsonResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/JsonResultVariantManager.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/NetworkActionResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/RangeActionResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/Result.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/ResultVariantManager.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/CnecResultExtensionTest.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/CracResultExtensionTest.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/JsonResultTest.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/ResultExtensionTest.java
  data/crac/crac-result-extensions/src/test/resources/small-crac-with-result-extensions.json
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
Labels: PR: ready-to-be-merged, enhancement

#204 fixing export for contingencies
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/ComplexContingency.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/CracImplJsonModule.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/ComplexContingencySerializer.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/RoundTripUtil.java
Labels: PR: waiting-for-info-author, bug

#203 rao result import export
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoResult.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/JsonRaoResult.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoResultTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoResultTest.java
  ra-optimisation/rao-api/src/test/resources/RaoResult.json
  ra-optimisation/rao-api/src/test/resources/RaoResultFailure.json
Labels: PR: waiting-for-info-reviewer, enhancement

#206 Thresholds cnec results
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/CnecResult.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/JsonResultTest.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
Labels: PR: waiting-for-review, enhancement

#205 Remedial action results extensions json io
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/NetworkActionDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/RangeActionDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/SimpleCracDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/NetworkActionSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/PstSetPointSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/TopologySerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/range_action/RangeActionSerializer.java
  data/crac/crac-result-extensions/pom.xml
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/JsonNetworkActionResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/JsonRangeActionResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/NetworkActionResult.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/NetworkActionResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/PstRangeResult.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/RangeActionResult.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/RangeActionResultExtension.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/Result.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/JsonResultTest.java
Labels: PR: waiting-for-review

#210 Add PowSyBl classic configuration in distribution dependencies
  distribution/pom.xml
Labels: PR: waiting-for-review

#214 Add CRAC synchronization in RaoTool
  distribution/src/main/resources/config.yml
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoTool.java
Labels: PR: waiting-for-review, bug

#198 Loopflow constraint
  data/crac/crac-loopflow-extension/src/main/java/com/farao_community/farao/data/crac_loopflow_extension/CracLoopFlowExtension.java
  data/crac/crac-loopflow-extension/src/test/java/com/farao_community/farao/data/crac_loopflow_extension/CracLoopFlowExtensionTest.java
  data/glsk/glsk-file/src/main/java/com/farao_community/farao/data/glsk/import_/EICode.java
  distribution/src/main/resources/config.yml
  flowbased-computation/flowbased-computation-impl/pom.xml
  flowbased-computation/flowbased-computation-impl/src/main/java/com/farao_community/farao/flowbased_computation/impl/LoopFlowComputation.java
  flowbased-computation/flowbased-computation-impl/src/test/java/com/farao_community/farao/flowbased_computation/impl/ExampleGenerator.java
  flowbased-computation/flowbased-computation-impl/src/test/java/com/farao_community/farao/flowbased_computation/impl/FlowBasedComputationImplTest.java
  flowbased-computation/flowbased-computation-impl/src/test/java/com/farao_community/farao/flowbased_computation/impl/LoopFlowComputationTest.java
  ra-optimisation/linear-rao/pom.xml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoModeller.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRaoProblem.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/fillers/MaxLoopFlowFiller.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoModellerTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoProblemTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/Rao.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRao.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/config/JsonSearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/config/SearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/config/SearchTreeRaoParametersConfigLoader.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/process/search_tree/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoUnitTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/config/JsonSearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/config/SearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: ready-to-be-merged
