Repository powsybl/powsybl-open-rao, pull requests merged in 2020-11, with the labels that each got.

#357 Handle Crac synchronization with aliases in flowbased module
  flowbased-computation/flowbased-computation-api/pom.xml
  flowbased-computation/flowbased-computation-api/src/main/java/com/farao_community/farao/flowbased_computation/tools/FlowbasedComputationTool.java
Labels: PR: ready-to-be-merged

#352 Second step in curative optimization
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/ResultVariantManager.java
  pom.xml
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/JsonLinearRaoResultTest.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/linear-rao/src/test/resources/RaoResultDefaultSensi.json
  ra-optimisation/linear-rao/src/test/resources/RaoResultFallbackSensi.json
  ra-optimisation/rao-api/pom.xml
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoInput.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoResult.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoTool.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoResultDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoResultSerializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoInputTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoResultTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoResultTest.java
  ra-optimisation/rao-api/src/test/resources/RaoResult.json
  ra-optimisation/rao-api/src/test/resources/RaoResultFailure.json
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracResultManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracVariantManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/LoopFlowUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearOptimizer.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblem.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizer.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerWithLoopFlows.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MnecViolationCostEvaluator.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/CracResultManagerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysisTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/LoopFlowUtilTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/PerimetersTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearOptimizerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/AbstractFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/LoopFlowViolationCostEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginObjectiveFunctionTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MnecViolationCostEvaluatorTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Tree.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/TreeTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/mock/RaoRunnerMock.java
  ra-optimisation/search-tree-rao/src/test/resources/RaoParametersWithoutSearchTreeParameters.json
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityInterface.java
Labels: PR: waiting-for-review

#344 Pst tap convention
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/JsonSerializationNames.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/NetworkActionDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/network_action/PstSetPointSerializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/PstSetpoint.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/CracImportExportTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/remedial_action/network_action/PstSetpointTest.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/JsonResultTest.java
Labels: PR: waiting-for-review

#356 Improve CRAC usage performance
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Crac.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoInputHelper.java
Labels: PR: waiting-for-review

#363 compute PTDF for loop-flows on preventive Cnecs only
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
Labels: PR: ready-to-be-merged

#365 Added a new "in-between" level of loopflow approximations
  data/crac/crac-loopflow-extension/src/main/java/com/farao_community/farao/data/crac_loopflow_extension/CnecLoopFlowExtension.java
  data/crac/crac-loopflow-extension/src/test/java/com/farao_community/farao/data/crac_loopflow_extension/CnecLoopFlowExtensionTest.java
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/CnecResult.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/CnecResultTest.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersSet.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithFallback.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithLoopFlowError.json
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracResultManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/LoopFlowUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizer.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerWithLoopFLowsParameters.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerWithLoopFlows.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/CracResultManagerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerWithLoopFlowsParametersTest.java
  ra-optimisation/rao-commons/src/test/resources/RaoParametersWithBoundaries.json
  ra-optimisation/rao-commons/src/test/resources/RaoPtdfParameters.json
  ra-optimisation/rao-commons/src/test/resources/RaoPtdfParametersUnknownField.json
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/resources/RaoParametersWithoutSearchTreeParameters.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersError.json
  ra-optimisation/search-tree-rao/src/test/resources/parameters.json
Labels: PR: ready-to-be-merged, PR: waiting-for-review

#366 Fix Sonar issue
  data/flowbased-domain/src/test/java/com/farao_community/farao/data/flowbased_domain/json/JsonFlowbasedDomainTest.java
Labels: PR: waiting-for-review

#368 RaoPtdfParameters small refactor
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersSet.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithFallback.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithLoopFlowError.json
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/JsonRaoPtdfParameters.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoPtdfParameters.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoPtdfParametersConfigLoader.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/JsonRaoPtdfParametersTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoPtdfParametersConfigLoaderTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoPtdfParametersTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/rao-commons/src/test/resources/RaoParametersWithBoundaries.json
  ra-optimisation/rao-commons/src/test/resources/RaoPtdfParameters.json
  ra-optimisation/rao-commons/src/test/resources/RaoPtdfParametersUnknownField.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersError.json
Labels: PR: waiting-for-review

#370 Add loadflowparameters to refprog builder
  data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramBuilder.java
  data/refprog/reference-program/src/test/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramBuilderTest.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
Labels: PR: waiting-for-review

#367 Acceptable lf augmentation
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersSet.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithFallback.json
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracResultManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/CracResultManagerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/search-tree-rao/src/test/resources/RaoParametersWithoutSearchTreeParameters.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersError.json
Labels: PR: waiting-for-review

#372 Migrate timestamp from DateTime to OffsetDateTime in CRAC import
  data/crac-io/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracImporter.java
  data/crac-io/crac-io-api/src/main/java/com/farao_community/farao/data/crac_io_api/CracImporters.java
  data/crac-io/crac-io-api/src/test/java/com/farao_community/farao/data/crac_io_api/CracExportersImportersTest.java
  data/crac-io/crac-io-api/src/test/java/com/farao_community/farao/data/crac_io_api/CracImporterMock.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/JsonImport.java
Labels: PR: waiting-for-review

#371 Correctly update RaoParameters extensions from json (new)
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/JsonLinearRaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/JsonSearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_default.json
  ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_update.json
Labels: PR: waiting-for-review

#376 Fix RAO results merging after curative optimization
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoProviderTest.java
Labels: PR: waiting-for-review

#375 Add a log to provide useful information when the sensitivity analysis fails
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityInterface.java
Labels: PR: waiting-for-review

#378 Handle properly relative thresholds on tie-lines
  data/crac/crac-impl/pom.xml
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/threshold/RelativeFlowThreshold.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/threshold/RelativeFlowThresholdTest.java
  data/crac/crac-impl/src/test/resources/TestCase12Nodes_with_Xnodes_different_imax.uct
Labels: PR: waiting-for-review

#379 Fix validity check for CNE file
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneExport.java
Labels: PR: waiting-for-review
