Repository powsybl/powsybl-open-rao, pull requests merged in 2021-08, with the labels that each got.

#492 US 16.5 : RA on constraint in specific country
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/AbstractRemedialAction.java
Labels: PR: ready-to-be-merged

#498 UCTE wildcards, alternative dev with TreeMultiMap
  data/crac/crac-creation-util/pom.xml
  data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/UcteBranchHelper.java
  data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/UcteBusHelper.java
  data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/UcteConnectable.java
  data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/UcteConnectableCollection.java
  data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/UcteMatchingResult.java
  data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/UcteNetworkHelper.java
  data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/UcteNetworkHelperProperties.java
  data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/UcteUtils.java
  data/crac/crac-creation-util/src/test/java/com/farao_community/farao/data/crac_creation_util/UcteBranchHelperTest.java
  data/crac/crac-creation-util/src/test/java/com/farao_community/farao/data/crac_creation_util/UcteBusHelperTest.java
  data/crac/crac-creation-util/src/test/java/com/farao_community/farao/data/crac_creation_util/UcteConnectableCollectionTest.java
  data/crac/crac-creation-util/src/test/java/com/farao_community/farao/data/crac_creation_util/UcteConnectableTest.java
  data/crac/crac-creation-util/src/test/java/com/farao_community/farao/data/crac_creation_util/UcteNetworkHelperTest.java
  data/crac/crac-creation-util/src/test/java/com/farao_community/farao/data/crac_creation_util/UcteUtilsTest.java
  data/crac/crac-creation-util/src/test/resources/TestCase16Nodes_with_different_imax.uct
  data/crac/crac-creation-util/src/test/resources/TestCase_severalVoltageLevels_Xnodes_8characters.uct
  data/crac/crac-creation-util/src/test/resources/TestCase_severalVoltageLevels_Xnodes_Ynode.uct
Labels: PR: waiting-for-review

#501 Consider GLSK not connected when bus is null
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationImpl.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationImplTest.java
Labels: bug, PR: waiting-for-review

#504 Fix parallel computating in curative
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
Labels: bug, PR: waiting-for-review
