Repository powsybl/powsybl-open-rao, pull requests merged in 2021-02, with the labels that each got.

#418 Skip PTDF computation in curative initial sensitivity analysis
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/ResultVariantManager.java
  ra-optimisation/linear-rao/src/main/java/com/farao_community/farao/linear_rao/LinearRao.java
  ra-optimisation/linear-rao/src/test/java/com/farao_community/farao/linear_rao/LinearRaoTest.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracResultManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracVariantManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinRelativeMarginFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizer.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluator.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/CracResultManagerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysisTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoDataTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearOptimizerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/AbstractFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/LoopFlowViolationCostEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginObjectiveFunctionTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MnecViolationCostEvaluatorTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/TreeParameters.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/TreeParametersTest.java
Labels: PR: waiting-for-review

#403 Export all expected measurements in CNE file (#12.8)
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneCnecsCreator.java
  data/crac-io/crac-io-cne/src/test/java/com/farao_community/farao/data/crac_io_cne/CneGenerationTest.java
Labels: PR: waiting-for-review

#421 improve logs
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
Labels: PR: waiting-for-review

#422 Add Z11 and relative margins to CNE export (#12.2) (simple implementation)
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/Cne.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneClassCreator.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneCnecsCreator.java
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneConstants.java
  data/crac-io/crac-io-cne/src/test/java/com/farao_community/farao/data/crac_io_cne/CneGenerationTest.java
  data/crac-io/crac-io-cne/src/test/resources/US2-3-crac1-standard.json
  data/crac-io/crac-io-cne/src/test/resources/US3-2-pst-direct.json
Labels: PR: waiting-for-review

#424 PTDF Boundaries with EI Code instead of Country Code
  commons/pom.xml
  commons/src/main/java/com/farao_community/farao/commons/CountryBoundary.java
  commons/src/main/java/com/farao_community/farao/commons/CountryEICode.java
  commons/src/main/java/com/farao_community/farao/commons/CountryGraph.java
  commons/src/main/java/com/farao_community/farao/commons/CountryUtil.java
  commons/src/main/java/com/farao_community/farao/commons/EICode.java
  commons/src/test/java/com/farao_community/farao/commons/CountryBoundaryTest.java
  commons/src/test/java/com/farao_community/farao/commons/CountryEICodeTest.java
  commons/src/test/java/com/farao_community/farao/commons/CountryGraphTest.java
  commons/src/test/java/com/farao_community/farao/commons/CountryUtilTest.java
  commons/src/test/java/com/farao_community/farao/commons/EICodeTest.java
  commons/src/test/resources/TestCase12Nodes.uct
  data/crac-io/crac-io-cne/pom.xml
  data/crac-io/crac-io-cne/src/main/java/com/farao_community/farao/data/crac_io_cne/CneClassCreator.java
  data/glsk/glsk-document-api/pom.xml
  data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/util/converters/GlskPointLinearGlskConverter.java
  data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/util/converters/GlskPointScalableConverter.java
  data/glsk/glsk-document-cim/pom.xml
  data/glsk/glsk-document-ucte/pom.xml
  data/glsk/glsk-virtual-hubs/src/main/java/com/farao_community/farao/data/glsk/virtual/hubs/GlskVirtualHubs.java
  data/refprog/reference-program/pom.xml
  data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/CountryNetPositionComputation.java
  data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/ReferenceExchangeData.java
  data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgram.java
  data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramArea.java
  data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramBuilder.java
  data/refprog/reference-program/src/test/java/com/farao_community/farao/data/refprog/reference_program/CountryNetPositionComputationTest.java
  data/refprog/reference-program/src/test/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramBuilderTest.java
  data/refprog/reference-program/src/test/java/com/farao_community/farao/data/refprog/reference_program/ReferenceProgramTest.java
  data/refprog/refprog-xml-importer/src/main/java/com/farao_community/farao/data/refprog/refprog_xml_importer/RefProgImporter.java
  data/refprog/refprog-xml-importer/src/test/java/com/farao_community/farao/data/refprog/refprog_xml_importer/RefProgImporterTest.java
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/ExampleGenerator.java
  ra-optimisation/linear-rao/src/test/resources/LinearRaoParameters.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoInputTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersSet.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithFallback.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithLoopFlowError.json
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/AbsolutePtdfSumsComputation.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/AbsolutePtdfSumsComputationTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/rao-commons/src/test/resources/glsk_proportional_12nodes_with_alegro.xml
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_default.json
  ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_update.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersMapError.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersMapError2.json
  util/src/test/java/com/farao_community/farao/util/EICodeTest.java
Labels: PR: waiting-for-review

#423 Add XnodeContingency (#14.4)
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Contingency.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/ContingencyAdder.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/ComplexContingency.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/ContingencyAdderImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/XnodeContingency.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/JsonSerializationNames.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/ContingencyDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/XnodeContingencySerializer.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/ComplexContingencyTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/ContingencyAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/CracFileTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/XnodeContingencyTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/CracImportExportTest.java
  data/crac/crac-impl/src/test/resources/TestCase12NodesHvdc.uct
  data/crac/crac-util/src/main/java/com/farao_community/farao/data/crac_util/CracCleaner.java
  data/crac/crac-util/src/test/java/com/farao_community/farao/data/crac_util/CracCleanerTest.java
Labels: PR: waiting-for-review

#426 Preventive and curative leaves-in-parallel
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersConfigLoader.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/TreeParameters.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/JsonSearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoParametersConfigLoaderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/TreeParametersTest.java
  ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_default.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: WIP

#425 Filter out range actions with initial setpoint outside of allowed range
  data/crac/crac-util/src/main/java/com/farao_community/farao/data/crac_util/CracCleaner.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFillerTest.java
  ra-optimisation/rao-commons/src/test/resources/small-crac.json
Labels: PR: waiting-for-review

#409 CRA in flowbased
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/CracResultUtil.java
  data/flowbased-domain/src/main/java/com/farao_community/farao/data/flowbased_domain/DataMonitoredBranch.java
  data/flowbased-domain/src/main/java/com/farao_community/farao/data/flowbased_domain/DataPostContingency.java
  data/flowbased-domain/src/main/java/com/farao_community/farao/data/flowbased_domain/DataPtdfPerCountry.java
  data/flowbased-domain/src/test/resources/dataDomain.json
  flowbased-computation/flowbased-computation-impl/src/main/java/com/farao_community/farao/flowbased_computation/impl/FlowbasedComputationImpl.java
  flowbased-computation/flowbased-computation-impl/src/test/java/com/farao_community/farao/flowbased_computation/impl/FlowbasedComputationImplTest.java
  flowbased-computation/flowbased-computation-impl/src/test/resources/crac.json
Labels: PR: waiting-for-info-reviewer, enhancement

#434 Fix relative margin threshold definition in LP
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinRelativeMarginFiller.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/AbstractFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinRelativeMarginFillerTest.java
Labels: PR: waiting-for-review, bug

#436 Pure MNECs patch & parallelization optimization
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluator.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluatorTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
Labels: PR: waiting-for-review, bug

#432 Add operator field to CNECs
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/cnec/Cnec.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/cnec/adder/CnecAdder.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/SimpleCrac.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/cnec/AbstractBranchCnec.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/cnec/AbstractCnec.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/cnec/FlowCnecImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/cnec/adder/AbstractCnecAdderImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/cnec/adder/FlowCnecAdderImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/deserializers/CnecDeserializer.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/json/serializers/BranchCnecSerializer.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/CracFileTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/FlowCnecAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/FlowCnecImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/json/CracImportExportTest.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/CnecResultExtensionTest.java
Labels: PR: waiting-for-review

#437 loop-flow computation does not shift NP of virtual hubs already disconnected by a contingency
  loopflow-computation/pom.xml
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/XnodeGlskHandler.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/XnodeGlskHandlerTest.java
  loopflow-computation/src/test/resources/TestCase12Nodes.uct
  loopflow-computation/src/test/resources/glsk_with_virtual_hubs.xml
  loopflow-computation/src/test/resources/network_with_virtual_hubs.xiidm
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/LoopFlowUtil.java
Labels: PR: waiting-for-review
