Repository powsybl/powsybl-open-rao, pull requests merged in 2021-06, with the labels that each got.

#473 Ignore PST filtering when TSO is not in "max-curative-pst-per-tso" map
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeTest.java
Labels: PR: waiting-for-correction, bug

#465 Exclude aligned PSTs with different initial setpoints (v2.4 patch)
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFillerTest.java
Labels: PR: ready-to-be-merged

#481 Rollback RangeAction setpoints after degradation in iterating LP (v2.4 patch)
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizer.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/iterating_linear_optimizer/IteratingLinearOptimizerTest.java
Labels: PR: waiting-for-review, bug

#477 LF computation : ignore LinearGlsk not connected to main network component (v2.4 patch)
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationTest.java
Labels: PR: waiting-for-review

#475 Sensitivity analysis with curative RA - API + Implementation
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/AbstractSimpleSensitivityProvider.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/AppliedRemedialActions.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/CnecSensitivityProvider.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/LoadflowProvider.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/MultipleSensitivityProvider.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/PtdfSensitivityProvider.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/RangeActionSensitivityProvider.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SensitivityAnalysisUtil.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityAdapter.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityInterface.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResult.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/AppliedRemedialActionsTest.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/MockSensiProvider.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/PtdfSensitivityProviderTest.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/RangeActionSensitivityProviderTest.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityAdapterTest.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityInterfaceTest.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResultTest.java
Labels: PR: waiting-for-review

#480 Max number curative ras
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeBloomer.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersConfigLoader.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/TreeParameters.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeTest.java
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: waiting-for-review

#482 Rollback RangeAction setpoints after degradation in iterating LP (master)
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/IteratingLinearOptimizer.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/IteratingLinearOptimizerTest.java
Labels: PR: waiting-for-review, bug

#479 Exclude aligned PSTs with different initial setpoints (master)
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProviderTest.java
Labels: PR: waiting-for-review

#487 US 19.6 : max number of TSOs in curative
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/RangeActionFilter.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeBloomer.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersConfigLoader.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/TreeParameters.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/RangeActionFilterTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeBloomerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeTest.java
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: waiting-for-review

#476 Enable secondary optimization of the preventive state
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/results/ObjectiveFunctionResult.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/PrePerimeterSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/SensitivityComputer.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/ToolProvider.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/CostEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/ObjectiveFunctionResultImpl.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/PrePerimeterSensitivityAnalysisTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/PerimeterOutput.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeBloomer.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeComputer.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersConfigLoader.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutput.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/SecondPreventiveAndCurativesRaoOutput.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeBloomerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersConfigLoaderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProviderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/output/SecondPreventiveAndCurativesRaoOutputTest.java
  ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_update.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/AppliedRemedialActions.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityAdapter.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityInterface.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResult.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityAdapterTest.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResultTest.java
Labels: PR: waiting-for-review
