Repository powsybl/powsybl-open-rao, pull requests merged in 2021-07, with the labels that each got.

#486 Add MNEC activation parameter
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/parameters/LinearOptimizerParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/parameters/RaoParameters.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersSet.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithFallback.json
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/LeafProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProviderTest.java
  ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_default.json
  ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_update.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersError.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersMapError.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersMapError2.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParametersStopCriterionError.json
Labels: PR: waiting-for-review, bug

#489 Adapt RA application in FB to crac refactoring
  data/crac/crac-result-extensions/src/main/java/com/farao_community/farao/data/crac_result_extensions/CracResultUtil.java
  data/crac/crac-result-extensions/src/test/java/com.farao_community.farao.data.crac_result_extensions/CracResultUtilTest.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/farao_community/farao/flowbased_computation/FlowbasedComputation.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/farao_community/farao/flowbased_computation/FlowbasedComputationProvider.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/farao_community/farao/flowbased_computation/tools/FlowbasedComputationTool.java
  flowbased-computation/flowbased-computation-api/src/test/java/com/farao_community/farao/flowbased_computation/FlowbasedComputationProviderMock.java
  flowbased-computation/flowbased-computation-api/src/test/java/com/farao_community/farao/flowbased_computation/FlowbasedComputationTest.java
  flowbased-computation/flowbased-computation-impl/src/main/java/com/farao_community/farao/flowbased_computation/impl/FlowbasedComputationImpl.java
  flowbased-computation/flowbased-computation-impl/src/test/java/com/farao_community/farao/flowbased_computation/impl/FlowbasedComputationImplTest.java
  flowbased-computation/flowbased-computation-impl/src/test/resources/crac_for_rao_result.json
Labels: PR: waiting-for-review, bug

#488 User Story #16.3: Activate remedial actions only after a specific constraint
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/JsonSerializationConstants.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/deserializers/NetworkActionArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/deserializers/OnFlowConstraintArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/deserializers/PstRangeActionArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/serializers/CracJsonSerializerModule.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/serializers/OnFlowConstraintSerializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/serializers/UsageRulesSerializer.java
  data/crac-io/crac-io-json/src/test/java/com/farao_community/farao/data/crac_io_json/CracImportExportTest.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Crac.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/RemedialActionAdder.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/usage_rule/OnFlowConstraint.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/usage_rule/OnFlowConstraintAdder.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/usage_rule/UsageMethod.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/AbstractRemedialAction.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/AbstractRemedialActionAdder.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/CracImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/NetworkElementImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/OnFlowConstraintAdderImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/OnFlowConstraintImpl.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/CracImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/OnFlowConstraintAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/OnFlowConstraintImplTest.java
  flowbased-computation/flowbased-computation-impl/src/main/java/com/farao_community/farao/flowbased_computation/impl/FlowbasedComputationImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/RangeActionFilter.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeInput.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/StateTree.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/RangeActionFilterTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProviderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeTest.java
Labels: PR: waiting-for-review

#478 LF computation : ignore LinearGlsk not connected to main network component (master)
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationImpl.java
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationWithXnodeGlskHandler.java
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/XnodeGlskHandler.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationImplTest.java
  loopflow-computation/src/test/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationWithXnodeGlskHandlerTest.java
Labels: PR: waiting-for-info-reviewer, PR: waiting-for-review, bug

#493 Add new UsageMethod to some classes
  data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/serializers/PstRangeActionResultArraySerializer.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProviderTest.java
Labels: PR: waiting-for-review, bug

#491 Take into account direct and opposite max flows in flowbased
  data/flowbased-domain/src/main/java/com/farao_community/farao/data/flowbased_domain/DataMonitoredBranch.java
  data/flowbased-domain/src/test/java/com/farao_community/farao/data/flowbased_domain/json/JsonFlowbasedDomainTest.java
  data/flowbased-domain/src/test/resources/dataDomain.json
  flowbased-computation/flowbased-computation-impl/src/main/java/com/farao_community/farao/flowbased_computation/impl/FlowbasedComputationImpl.java
Labels: PR: waiting-for-review, bug

#494 Configure combination of NetworkAction to guide/speed-up the search tree
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/NetworkActionCombination.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/PerimeterOutput.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeBloomer.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/NetworkActionCombinationTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeBloomerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeTest.java
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: waiting-for-review
