Repository powsybl/powsybl-open-rao, pull requests merged in 2021-11, with the labels that each got.

#542 2nd preventive advanced run conditions
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/Rao.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoProvider.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/parameters/RaoParameters.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/rao_mock/AnotherRaoProviderMock.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/rao_mock/RaoProviderMock.java
  ra-optimisation/rao-api/src/test/resources/RaoParameters.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersSet.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithExtension.json
  ra-optimisation/rao-api/src/test/resources/RaoParametersWithFallback.json
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersConfigLoader.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/UnoptimizedRaoOutput.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersConfigLoaderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProviderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/output/UnoptimizedRaoOutputTest.java
  ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_update.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: waiting-for-review

#538 Ignore Alegro in PTDF sum when disconnected by outage
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/XnodeGlskHandler.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/AbsolutePtdfSumsComputation.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/AbsolutePtdfSumsComputationTest.java
  ra-optimisation/rao-commons/src/test/resources/glsk_with_virtual_hubs.xml
  ra-optimisation/rao-commons/src/test/resources/network_with_alegro_hub.xiidm
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
Labels: bug, PR: waiting-for-review

#545 Accept feasible MIP solutions
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/IteratingLinearOptimizer.java
Labels: PR: waiting-for-review

#536 Ignore glsk on disconnected line
  data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/util/ZonalDataFromGlskDocument.java
  data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/util/converters/GlskPointLinearGlskConverter.java
  data/glsk/glsk-document-cim/src/test/java/com/farao_community/farao/data/glsk/api/util/converters/GlskPointLinearGlskConverterTest.java
  data/glsk/glsk-document-cim/src/test/resources/GlskB43ParticipationFactorGskZero.xml
  data/glsk/glsk-document-cim/src/test/resources/GlskB43ParticipationFactorLskZero.xml
  data/glsk/glsk-document-ucte/src/test/java/com/farao_community/farao/data/glsk/ucte/UcteGlskValueProviderTest.java
  data/glsk/glsk-document-ucte/src/test/resources/TestZeroGsk.xml
  data/glsk/glsk-document-ucte/src/test/resources/TestZeroLsk.xml
  distribution/pom.xml
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResult.java
Labels: PR: waiting-for-review

#530 Bug fixing in replacement of 8th character
  data/crac-creation/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation/util/ucte/UcteBusHelper.java
  data/crac-creation/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation/util/ucte/UcteConnectableCollection.java
  data/crac-creation/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation/util/ucte/UcteNetworkAnalyzer.java
  data/crac-creation/crac-creation-util/src/test/java/com/farao_community/farao/data/crac_creation/util/ucte/UcteBusHelperTest.java
  data/crac-creation/crac-creation-util/src/test/java/com/farao_community/farao/data/crac_creation/util/ucte/UcteCnecElementHelperTest.java
  data/crac-creation/crac-creation-util/src/test/java/com/farao_community/farao/data/crac_creation/util/ucte/UcteConnectableCollectionTest.java
Labels: bug, PR: waiting-for-review

#532 Use the sensi with RA feature in flowbased
  flowbased-computation/flowbased-computation-impl/src/main/java/com/farao_community/farao/flowbased_computation/impl/FlowbasedComputationImpl.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/AppliedRemedialActions.java
Labels: PR: waiting-for-review, cleaning

#547 Attempt to render MIP results completely reproducible
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/FaraoMPConstraint.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/FaraoMPSolver.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/FaraoMPVariable.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblem.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblemResult.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/ContinuousRangeActionGroupFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/DiscretePstGroupFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/DiscretePstTapFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/UnoptimizedCnecFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/LoopFlowViolationCostEvaluator.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResult.java
Labels: PR: waiting-for-review

#554 fix CRA PST in second preventive rao result
  data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/serializers/PstRangeActionResultArraySerializer.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/PerimeterOutput.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/SecondPreventiveAndCurativesRaoOutput.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/PerimeterOutputTest.java
Labels: PR: waiting-for-review
