Repository powsybl/powsybl-open-rao, pull requests merged in 2021-10, with the labels that each got.

#522 BusIdMatchPolicy: replace the 8th character by a wildcard
  data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteBusHelper.java
  data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteNetworkAnalyzer.java
  data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteNetworkAnalyzerProperties.java
  data/crac/crac-creation-util/src/test/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteBusHelperTest.java
Labels: enhancement, PR: waiting-for-review

#505 Compute sensitivities on HVDC
  commons/src/main/java/com/farao_community/farao/commons/CountryGraph.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/NetworkElementImpl.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/NetworkElementImplTest.java
  data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/util/converters/GlskPointLinearGlskConverter.java
  data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/util/converters/GlskPointScalableConverter.java
  data/refprog/reference-program/src/main/java/com/farao_community/farao/data/refprog/reference_program/CountryNetPositionComputation.java
  flowbased-computation/flowbased-computation-api/src/test/java/com/farao_community/farao/flowbased_computation/NetworkUtil.java
  pom.xml
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/LoadflowProvider.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/RangeActionSensitivityProvider.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/RangeActionSensitivityProviderTest.java
  sensitivity-analysis/src/test/resources/TestCase16NodesWithHvdc.xiidm
Labels: PR: waiting-for-review

#523 Better cost handling in RaoResult
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputationImpl.java
  loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowResult.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/PrePerimeterSensitivityAnalysis.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutput.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutputTest.java
Labels: bug, PR: ready-to-be-merged
