Repository powsybl/powsybl-open-rao, pull requests merged in 2021-03, with the labels that each got.

#438 PTDF boundary with n zones (n>=1) for relative margin computation
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/RaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/ZoneToZonePtdfDefinition.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/RaoParametersTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/ZoneToZonePtdfDefinitionTest.java
  ra-optimisation/rao-api/src/test/java/com/farao_community/farao/rao_api/json/JsonRaoParametersTest.java
  ra-optimisation/rao-api/src/test/resources/RaoParametersSet.json
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/AbsolutePtdfSumsComputation.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/AbsolutePtdfSumsComputationTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/rao-commons/src/test/resources/glsk_proportional_12nodes_with_alegro.xml
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
Labels: PR: waiting-for-review

#441 Fix behaviour when a LinearGlsk is missing
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/AbsolutePtdfSumsComputation.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/AbsolutePtdfSumsComputationTest.java
Labels: PR: waiting-for-review, bug

#442 Allow import of multiple blocks in GLSK
  data/glsk/glsk-document-ucte/src/main/java/com/farao_community/farao/data/glsk/ucte/UcteGlskDocument.java
  data/glsk/glsk-document-ucte/src/test/java/com/farao_community/farao/data/glsk/ucte/UcteGlskDocumentImporterTest.java
  data/glsk/glsk-document-ucte/src/test/java/com/farao_community/farao/data/glsk/ucte/UcteGlskValueProviderTest.java
  data/glsk/glsk-document-ucte/src/test/resources/TestMultiShare1.xml
  data/glsk/glsk-document-ucte/src/test/resources/TestMultiShare2.xml
Labels: PR: ready-to-be-merged

#433 Core CC "Share of RA" MIP implementation
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/FlowCnecImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/utils/CommonCracCreation.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/CracResultManager.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/InitialSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearOptimizer.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/LinearProblem.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinRelativeMarginFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/OperatorsNotToOptimizeFiller.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluator.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginObjectiveFunction.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/OperatorsNotToOptimizeFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/mocks/MPSolverMock.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/mocks/MPVariableMock.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginEvaluatorTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/objective_function_evaluator/MinMarginObjectiveFunctionTest.java
  ra-optimisation/rao-commons/src/test/resources/small-crac.json
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/JsonSearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoParametersConfigLoader.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/StateTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/TreeParameters.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/JsonSearchTreeRaoParametersTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoParametersConfigLoaderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeRaoProviderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/SearchTreeTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/StateTreeTest.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/TreeParametersTest.java
  ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_default.json
  ra-optimisation/search-tree-rao/src/test/resources/RaoParameters_update.json
  ra-optimisation/search-tree-rao/src/test/resources/SearchTreeRaoParameters.json
Labels: PR: waiting-for-review

#445 Import all loads and generators in network post-processing
  distribution/src/main/resources/core-cc-ucte-postProcessor.groovy
Labels: PR: waiting-for-review

#450 Update config.yml example
  distribution/src/main/resources/config.yml
Labels: PR: waiting-for-review

#453 Fix imported GLSK when generator inital target power is not in merit order block range
  data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/util/converters/GlskPointScalableConverter.java
  data/glsk/glsk-document-cse/src/test/java/com/farao_community/farao/data/glsk/cse/CseGlskDocumentImporterTest.java
  data/glsk/glsk-document-cse/src/test/resources/testGlsk.xml
Labels: PR: waiting-for-review, bug

#451 Add getLocation methods to CRAC API
  data/crac/crac-api/pom.xml
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/NetworkElement.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/RemedialAction.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/cnec/Cnec.java
  data/crac/crac-api/src/test/java/com/farao_community/farao/data/crac_api/NetworkElementTest.java
  data/crac/crac-api/src/test/resources/TestCase12NodesWithSwitch.uct
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/FlowCnecImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/remedial_action/range_action/PstRangeActionImplTest.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoData.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/RaoUtil.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/RaoUtilTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com.farao_community.farao.search_tree_rao/LeafTest.java
Labels: PR: waiting-for-review
