Repository powsybl/powsybl-open-rao, pull requests merged in 2021-09, with the labels that each got.

#503 Correction in PrePerimeterSensitivityAnalysis
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/PrePerimeterSensitivityAnalysis.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/PrePerimeterSensitivityOutput.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/objective_function_evaluator/ObjectiveFunctionHelper.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/PrePerimeterSensitivityAnalysisTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/PrePerimeterSensitivityOutputTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/ObjectiveFunctionHelper.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
Labels: PR: waiting-for-review

#510 Import hvdc from crac
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/JsonSerializationConstants.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/deserializers/CracDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/deserializers/HvdcRangeActionArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/deserializers/HvdcRangeArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/serializers/CracJsonSerializerModule.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/serializers/CracSerializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/serializers/HvdcRangeActionSerializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/serializers/HvdcRangeSerializer.java
  data/crac-io/crac-io-json/src/test/java/com/farao_community/farao/data/crac_io_json/CracImportExportTest.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Crac.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/range_action/HvdcRange.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/range_action/HvdcRangeAction.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/range_action/HvdcRangeActionAdder.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/range_action/HvdcRangeAdder.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/CracImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/HvdcRangeActionAdderImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/HvdcRangeActionImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/HvdcRangeAdderImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/HvdcRangeImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/NetworkElementImpl.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/CracImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/HvdcRangeActionAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/HvdcRangeActionImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/HvdcRangeAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/HvdcRangeImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/utils/NetworkImportsUtil.java
  data/crac/crac-impl/src/test/resources/utils/TestCase16NodesWithHvdc.xiidm
Labels: PR: waiting-for-correction

#512 Refactor StateTree
  data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/serializers/PstRangeActionResultArraySerializer.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/StateTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/state_tree/BasecaseScenario.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/state_tree/ContingencyScenario.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/state_tree/StateTree.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/PerimetersTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProviderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/StateTreeTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/state_tree/BasecaseScenarioTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/state_tree/ContingencyScenarioTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/state_tree/StateTreeTest.java
Labels: PR: waiting-for-review

#511 add parameters to CRAC creators
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/CracCreator.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/CracCreators.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/parameters/CracCreationParameters.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/parameters/CracCreationParametersDeserializer.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/parameters/CracCreationParametersJsonModule.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/parameters/CracCreationParametersSerializer.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/parameters/JsonCracCreationParameters.java
  data/crac/crac-creator-api/src/test/java/com/farao_community/farao/data/crac_creator_api/CracCreatorsTest.java
  data/crac/crac-creator-api/src/test/java/com/farao_community/farao/data/crac_creator_api/mock/CracCreatorMock.java
  data/crac/crac-creator-api/src/test/java/com/farao_community/farao/data/crac_creator_api/parameters/CracCreationParametersJsonTest.java
  data/crac/crac-creator-api/src/test/java/com/farao_community/farao/data/crac_creator_api/parameters/CracCreationParametersTest.java
  data/crac/crac-creator-api/src/test/resources/parameters/crac-creator-parameters-nok.json
  data/crac/crac-creator-api/src/test/resources/parameters/crac-creator-parameters-ok.json
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/JsonRaoParameters.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersDeserializer.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersJsonModule.java
  ra-optimisation/rao-api/src/main/java/com/farao_community/farao/rao_api/json/RaoParametersSerializer.java
Labels: PR: waiting-for-review

#513 Network-action automatons
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Instant.java
  data/crac/crac-api/src/test/java/com/farao_community/farao/data/crac_api/InstantTest.java
  data/rao-result/rao-result-api/pom.xml
  data/rao-result/rao-result-api/src/main/java/com/farao_community/farao/data/rao_result_api/OptimizationState.java
  data/rao-result/rao-result-api/src/test/java/com/farao_community/farao/data/rao_result_api/OptimizationStateTest.java
  data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/RaoResultJsonConstants.java
  data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/deserializers/CostResultMapDeserializer.java
  data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/deserializers/FlowCnecResultArrayDeserializer.java
  data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/serializers/CostResultMapSerializer.java
  data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/serializers/FlowCnecResultArraySerializer.java
  data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/serializers/PstRangeActionResultArraySerializer.java
  data/rao-result/rao-result-json/src/test/java/com/farao_community/farao/data/rao_result_json/RaoResultExporterTest.java
  data/rao-result/rao-result-json/src/test/java/com/farao_community/farao/data/rao_result_json/RaoResultJsonConstantsTest.java
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/PrePerimeterSensitivityAnalysis.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/PerimeterOutput.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLogger.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/AutomatonOptimizationResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutput.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/SecondPreventiveAndCurativesRaoOutput.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/PerimeterOutputTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoLoggerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/output/AutomatonOptimizationResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutputTest.java
Labels: PR: waiting-for-review

#515 Relative PST sensitivity threshold
  ra-optimisation/rao-commons/src/main/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFiller.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/CoreProblemFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/MnecFillerTest.java
  ra-optimisation/rao-commons/src/test/java/com/farao_community/farao/rao_commons/linear_optimisation/fillers/UnoptimizedCnecFillerTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeProblem.java
Labels: bug, PR: ready-to-be-merged

#518 Fix AFTER_ARA bug in RaoResult
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutput.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/output/PreventiveAndCurativesRaoOutputTest.java
Labels: bug, PR: ready-to-be-merged

#517 Enable 2nd preventive RAO with advanced curative stop criteria
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProvider.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/SearchTreeRaoProviderTest.java
Labels: PR: ready-to-be-merged

#520 Bugfix infinitely iterating linear rao
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/RangeActionFilter.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/SearchTree.java
Labels: PR: waiting-for-correction

#516 development of crac creators -good practices
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/CracCreationContext.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/CracCreationReport.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/CracCreator.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/ElementaryCreationContext.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/ImportStatus.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/std_creation_context/BranchCnecCreationContext.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/std_creation_context/HvdcRangeActionCreationContext.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/std_creation_context/RemedialActionCreationContext.java
  data/crac/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creator_api/std_creation_context/StandardCracCreationContext.java
  data/crac/crac-creator-api/src/test/java/com/farao_community/farao/data/crac_creator_api/CracCreationReportTest.java
  data/crac/crac-creator-api/src/test/java/com/farao_community/farao/data/crac_creator_api/ImportStatusTest.java
  data/crac/crac-creator-api/src/test/java/com/farao_community/farao/data/crac_creator_api/mock/CracCreationContextMock.java
Labels: PR: waiting-for-review
