Repository powsybl/powsybl-open-rao, pull requests merged in 2023-12, with the labels that each got.

#840 [CSA-79] Import FlowCNECs from AssessedElement defined with ConductingEquipment
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileConstants.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/AbstractCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/AngleCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/CsaProfileCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/FlowCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/VoltageCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/CsaProfileRemedialActionsCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/resources/csa_profile.sparql
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreationTestUtil.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreatorTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/AngleCnecCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/FlowCnecCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/VoltageCnecCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/contingencies/ContingenciesCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_30_CustomProfiles.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_33_TestExample.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_42_CustomExample.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_76_ContingenciesWithoutTSOorName.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_79_1.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_SPS_2_ValidProflies.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_SPS_3_InvalidProflies.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_TestConfiguration_TC2_Draft_v14Apr2023.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_Test_With_Rejected_Files.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_Test_With_Rejected_Files_Operational_Limits.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/TC2_OperationalLimits.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/TestCaseWithoutSubdirectory.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/TestConfiguration_TC1_v29Mar2023.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/Test_With_Refused_Contingencies.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/csa-11/CSA_11_3_OnFlowConstraint.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/csa-13/CSA_13_3_ValidProfiles.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/csa-13/CSA_13_4_InvalidProfiles.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/csa-23/CSA_23_1_ValidProfiles.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/csa-23/CSA_23_2_InvalidProfiles.zip
Labels: PR: waiting-for-review

#845 [CSA-82] More efficient and homogeneous query of CSA headers
  data/crac-creation/crac-creator-csa-profiles/pom.xml
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/CsaProfileCrac.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileConstants.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracUtils.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/AngleCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/CsaProfileCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/contingency/CsaProfileContingencyCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/CsaProfileRemedialActionsCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/importer/CsaProfileCracImporter.java
  data/crac-creation/crac-creator-csa-profiles/src/main/resources/csa_profile.sparql
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreationTestUtil.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracFilteringTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracUtilsTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/cnec/FlowCnecCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/contingencies/ContingenciesCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/TopologicalActionCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/importer/CsaProfileCracImporterTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_82_FilterBadTS.zip
Labels: PR: waiting-for-review

#850 Fix unoptimized CNECs with PSTs in case of negative sensitivity
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/UnoptimizedCnecFiller.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/UnoptimizedCnecFillerPstLimitationRuleTest.java
Labels: bug, PR: waiting-for-review

#846 Improve RA adders APIs
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/network_action/NetworkActionAdder.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/range_action/CounterTradeRangeActionAdder.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/range_action/HvdcRangeActionAdder.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/range_action/InjectionRangeActionAdder.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/range_action/PstRangeActionAdder.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/CounterTradeRangeActionAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/CounterTradeRangeActionImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/HvdcRangeActionAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/HvdcRangeActionImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/InjectionRangeActionAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/InjectionRangeActionImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/InjectionSetpointAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/NetworkActionAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/PstRangeActionAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/PstRangeActionImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/PstSetpointAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/StandardRangeAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/SwitchPairAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/TapRangeAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/TopologicalActionAdderImplTest.java
  data/rao-result/rao-result-impl/src/test/java/com/farao_community/farao/data/rao_result_impl/RaoResultImplTest.java
  data/rao-result/rao-result-json/src/test/java/com/farao_community/farao/data/rao_result_json/RaoResultRoundTripTest.java
  data/result-exporter/core-cne-exporter/src/test/java/com/farao_community/farao/data/core_cne_exporter/CoreCneRemedialActionsCreatorTest.java
  monitoring/angle-monitoring/src/test/java/com/farao_community/farao/monitoring/angle_monitoring/AngleMonitoringTest.java
  monitoring/angle-monitoring/src/test/java/com/farao_community/farao/monitoring/angle_monitoring/json/JsonAngleMonitoringResultTest.java
  monitoring/voltage-monitoring/src/test/java/com/farao_community/farao/monitoring/voltage_monitoring/VoltageMonitoringTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/castor/algorithm/AutomatonSimulatorTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimizationTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/commons/NetworkActionCombinationTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/commons/optimization_perimeters/AbstractOptimizationPerimeterTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/IteratingLinearOptimizerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/result/impl/RangeActionActivationResultImplTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeBloomerTest.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/AppliedRemedialActionsTest.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/SystematicSensitivityResultTest.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/ra_sensi_handler/HvdcRangeActionSensiHandlerTest.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/ra_sensi_handler/InjectionRangeActionSensiHandlerTest.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/ra_sensi_handler/PstRangeActionSensiHandlerTest.java
Labels: PR: waiting-for-review

#849 overriding fields with SSI and SSH
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/CsaProfileCrac.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileConstants.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracUtils.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/CsaProfileRemedialActionsCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/OnConstraintUsageRuleHelper.java
  data/crac-creation/crac-creator-csa-profiles/src/main/resources/csa_profile.sparql
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreationTestUtil.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreatorTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_36_3_CustomExample.zip
Labels: PR: waiting-for-review

#854 Import ARAs from RA profile only
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/CsaProfileCrac.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileConstants.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/CsaProfileRemedialActionsCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/resources/csa_profile.sparql
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/AutoRemedialActionTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/remedial_action/TopologicalActionCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA-83.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_SPS_3_InvalidProfiles.zip
Labels: PR: waiting-for-review

#848 [ALG-122] Simplify SWE CNE creator
  data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/parameters/JsonVoltageCnecsCreationParameters.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Instant.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/InstantImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/PstRangeActionImpl.java
  data/rao-result/rao-result-api/src/main/java/com/farao_community/farao/data/rao_result_api/RaoResultClone.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/farao_community/farao/data/swe_cne_exporter/SweAdditionalConstraintSeriesCreator.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/farao_community/farao/data/swe_cne_exporter/SweCne.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/farao_community/farao/data/swe_cne_exporter/SweCneExporter.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/farao_community/farao/data/swe_cne_exporter/SweCneHelper.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/farao_community/farao/data/swe_cne_exporter/SweCneUtil.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/farao_community/farao/data/swe_cne_exporter/SweRemedialActionSeriesCreator.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/farao_community/farao/data/swe_cne_exporter/SweAdditionalConstraintSeriesCreatorTest.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/farao_community/farao/data/swe_cne_exporter/SweCneDivergentAngleMonitoringTest.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/farao_community/farao/data/swe_cne_exporter/SweCneTest.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/farao_community/farao/data/swe_cne_exporter/SweRemedialActionSeriesCreatorTest.java
  data/result-exporter/swe-cne-exporter/src/test/resources/SweCNE.xml
  data/result-exporter/swe-cne-exporter/src/test/resources/SweCNEDivergentAngleMonitoring_Z01.xml
  monitoring/angle-monitoring/src/main/java/com/farao_community/farao/monitoring/angle_monitoring/RaoResultWithAngleMonitoring.java
  monitoring/angle-monitoring/src/test/java/com/farao_community/farao/monitoring/angle_monitoring/RaoResultWithAngleMonitoringTest.java
Labels: PR: waiting-for-correction
