Repository powsybl/powsybl-open-rao, pull requests merged in 2023-01, with the labels that each got.

#707 Fix bug in SearchTreeRaoParameters
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/parameters/SearchTreeRaoParameters.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/castor/parameters/SearchTreeRaoParametersTest.java
Labels: bug, PR: waiting-for-review

#708 2P condition
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java
Labels: PR: ready-to-be-merged

#712 Fix bug in parallelization
  monitoring/angle-monitoring/src/main/java/com/farao_community/farao/monitoring/angle_monitoring/AngleMonitoring.java
  monitoring/voltage-monitoring/src/main/java/com/farao_community/farao/monitoring/voltage_monitoring/VoltageMonitoring.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
Labels: bug, PR: waiting-for-review

#709 Update CSE crac xsd to v4.23
  data/crac-creation/crac-creator-cse/src/main/java/com/farao_community/farao/data/crac_creation/creator/cse/CseCracImporter.java
  data/crac-creation/crac-creator-cse/src/main/resources/com/farao_community/farao/data/crac_creation/creator/cse/xsd/crac-document_4_23.xsd
Labels: PR: waiting-for-review

#715 Add auto to 2P
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java
Labels: PR: waiting-for-review

#716 Minor CIM fix
  data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/cnec/MonitoredSeriesCreationContext.java
Labels: bug, PR: waiting-for-review

#717 Allow running a RAO on an auto state only
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorOneStateOnly.java
Labels: enhancement, PR: waiting-for-review

#719 Auto fixes
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/AutomatonSimulator.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorOneStateOnly.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/castor/algorithm/AutomatonSimulatorTest.java
Labels: bug, PR: waiting-for-review
