Repository powsybl/powsybl-open-rao, pull requests merged in 2023-08, with the labels that each got.

#775 Csa 25 voltage ra in crac api
  data/crac-creation/crac-creator-cim/src/test/java/com/farao_community/farao/data/crac_creation/creator/cim/parameters/JsonVoltageCnecsCreationParametersTest.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/JsonSerializationConstants.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/deserializers/HvdcRangeActionArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/deserializers/InjectionRangeActionArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/deserializers/NetworkActionArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/deserializers/OnVoltageConstraintArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/deserializers/PstRangeActionArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/serializers/CracJsonSerializerModule.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/serializers/OnVoltageConstraintSerializer.java
  data/crac-io/crac-io-json/src/main/java/com/farao_community/farao/data/crac_io_json/serializers/UsageRulesSerializer.java
  data/crac-io/crac-io-json/src/test/java/com/farao_community/farao/data/crac_io_json/CracImportExportTest.java
  data/crac-io/crac-io-json/src/test/java/com/farao_community/farao/data/crac_io_json/JsonRetrocompatibilityTest.java
  data/crac-io/crac-io-json/src/test/resources/retrocompatibility/v1/crac-v1.7.json
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/RemedialActionAdder.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/usage_rule/OnVoltageConstraint.java
  data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/usage_rule/OnVoltageConstraintAdder.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/AbstractRemedialActionAdder.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/OnAngleConstraintAdderImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/OnFlowConstraintAdderImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/OnInstantAdderImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/OnVoltageConstraintAdderImpl.java
  data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/OnVoltageConstraintImpl.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/OnAngleConstraintAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/OnVoltageConstraintAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/OnVoltageConstraintImplTest.java
  data/crac/crac-impl/src/test/java/com/farao_community/farao/data/crac_impl/utils/ExhaustiveCracCreation.java
  monitoring/angle-monitoring/src/test/java/com/farao_community/farao/monitoring/angle_monitoring/json/JsonAngleMonitoringResultTest.java
  monitoring/voltage-monitoring/src/test/java/com/farao_community/farao/monitoring/voltage_monitoring/json/JsonVoltageMonitoringResultTest.java
Labels: PR: waiting-for-review

#771 Upgrade to olf 1.2.3
  pom.xml
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withExtensions.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withOLFParams.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withPartialExtensions.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withoutExtensions.json
Labels: PR: WIP

#785 Fix csa test
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/farao_community/farao/data/crac_creation/creator/csa_profile/crac_creator/CsaProfileCracCreatorTest.java
Labels: bug, PR: waiting-for-review

#777 Fix 2P ARA skipped opt
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/IteratingLinearOptimizer.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/LinearProblemBuilder.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/RangeActionActivationResultImpl.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/BestTapFinderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/result/impl/LinearProblemResultTest.java
  sensitivity-analysis/src/main/java/com/farao_community/farao/sensitivity_analysis/AppliedRemedialActions.java
  sensitivity-analysis/src/test/java/com/farao_community/farao/sensitivity_analysis/AppliedRemedialActionsTest.java
Labels: PR: WIP
