Repository powsybl/powsybl-open-rao, pull requests merged in 2023-03, with the labels that each got.

#739 Demote some logs
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/commons/parameters/UnoptimizedCnecParameters.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/UnoptimizedCnecFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTree.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/search_tree/algorithms/SearchTreeTest.java
  util/src/main/java/com/farao_community/farao/util/MultipleNetworkPool.java
Labels: PR: waiting-for-review

#740 OR-Tools version update to 9.5 + better encapsulation
  pom.xml
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/ContinuousRangeActionGroupFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/CoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/DiscretePstGroupFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/DiscretePstTapFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MaxLoopFlowFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MaxMinMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MaxMinRelativeMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MnecFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/RaUsageLimitsFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/UnoptimizedCnecFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/FaraoMPConstraint.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/FaraoMPObjective.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/FaraoMPSolver.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/FaraoMPVariable.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/linear_problem/LinearProblemBuilder.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/AbstractFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/ContinuousRangeActionGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/CoreProblemFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/DiscretePstGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/DiscretePstTapFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/MnecFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/RaUsageLimitsFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/UnoptimizedCnecFillerMarginDecreaseRuleTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/fillers/UnoptimizedCnecFillerPstLimitationRuleTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/mocks/MPConstraintMock.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/mocks/MPObjectiveMock.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/mocks/MPSolverMock.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/linear_optimisation/algorithms/mocks/MPVariableMock.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/result/impl/LinearProblemResultTest.java
Labels: PR: WIP

#745 Remove SearchTreeRaoResult Interface
  data/rao-result/rao-result-api/src/main/java/com/farao_community/farao/data/rao_result_api/RaoResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/api/SearchTreeRaoResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/FailedRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/OneStateOnlyRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/PreventiveAndCurativesRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/UnoptimizedRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/result/impl/FailedRaoResultImplTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/result/impl/OneStateOnlyRaoResultImplTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/farao_community/farao/search_tree_rao/result/impl/PreventiveAndCurativesRaoResultImplTest.java
Labels: PR: ready-to-be-merged

#735 Enrich CracCreation APIs
  data/crac-creation/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creation/creator/api/CracCreationContext.java
  data/crac-creation/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creation/creator/api/ElementaryCreationContext.java
  data/crac-creation/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creation/creator/api/std_creation_context/BranchCnecCreationContext.java
  data/crac-creation/crac-creator-api/src/main/java/com/farao_community/farao/data/crac_creation/creator/api/std_creation_context/UcteCracCreationContext.java
  data/crac-creation/crac-creator-api/src/test/java/com/farao_community/farao/data/crac_creation/creator/api/mock/CracCreationContextMock.java
  data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/CimCracCreationContext.java
  data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/CimCracCreator.java
  data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/cnec/AngleCnecCreationContext.java
  data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/remedial_action/RemedialActionSeriesCreationContext.java
  data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/parameters/VoltageThreshold.java
  data/crac-creation/crac-creator-cim/src/test/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/CimCracCreatorTest.java
  data/crac-creation/crac-creator-cse/src/main/java/com/farao_community/farao/data/crac_creation/creator/cse/CseCracCreationContext.java
  data/crac-creation/crac-creator-fb-constraint/src/main/java/com/farao_community/farao/data/crac_creation/creator/fb_constraint/crac_creator/FbConstraintCreationContext.java
  data/rao-result/rao-result-api/src/main/java/com/farao_community/farao/data/rao_result_api/RaoResult.java
  data/result-exporter/core-cne-exporter/src/main/java/com/farao_community/farao/data/core_cne_exporter/CoreCne.java
  data/result-exporter/core-cne-exporter/src/main/java/com/farao_community/farao/data/core_cne_exporter/CoreCneCnecsCreator.java
  data/result-exporter/core-cne-exporter/src/main/java/com/farao_community/farao/data/core_cne_exporter/CoreCneExporter.java
  data/result-exporter/core-cne-exporter/src/main/java/com/farao_community/farao/data/core_cne_exporter/CoreCneRemedialActionsCreator.java
  data/result-exporter/core-cne-exporter/src/test/java/com/farao_community/farao/data/core_cne_exporter/CoreCneRemedialActionsCreatorTest.java
  data/result-exporter/core-cne-exporter/src/test/java/com/farao_community/farao/data/core_cne_exporter/CoreCneTest.java
  data/result-exporter/core-cne-exporter/src/test/java/com/farao_community/farao/data/core_cne_exporter/MockCracCreationContext.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/farao_community/farao/data/swe_cne_exporter/SweAdditionalConstraintSeriesCreator.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/farao_community/farao/data/swe_cne_exporter/MockCracCreationContext.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/farao_community/farao/data/swe_cne_exporter/SweAdditionalConstraintSeriesCreatorTest.java
Labels: PR: waiting-for-review
