Repository powsybl/powsybl-open-rao, pull requests merged in 2024-04, with the labels that each got.

#956 Improve VirtualHubs configuration importer
  data/glsk/glsk-virtual-hubs/src/main/java/com/powsybl/openrao/data/glsk/virtual/hubs/GlskVirtualHubs.java
  data/glsk/glsk-virtual-hubs/src/test/java/com/powsybl/openrao/data/glsk/virtual/hubs/GlskVirtualHubsTest.java
  data/virtual-hubs/virtual-hubs-api/src/main/java/com/powsybl/openrao/virtualhubs/BorderDirection.java
  data/virtual-hubs/virtual-hubs-api/src/main/java/com/powsybl/openrao/virtualhubs/MarketArea.java
  data/virtual-hubs/virtual-hubs-api/src/main/java/com/powsybl/openrao/virtualhubs/VirtualHub.java
  data/virtual-hubs/virtual-hubs-api/src/main/java/com/powsybl/openrao/virtualhubs/VirtualHubsConfiguration.java
  data/virtual-hubs/virtual-hubs-api/src/test/java/com/powsybl/openrao/virtualhubs/BorderDirectionTest.java
  data/virtual-hubs/virtual-hubs-api/src/test/java/com/powsybl/openrao/virtualhubs/MarketAreaTest.java
  data/virtual-hubs/virtual-hubs-api/src/test/java/com/powsybl/openrao/virtualhubs/VirtualHubTest.java
  data/virtual-hubs/virtual-hubs-api/src/test/java/com/powsybl/openrao/virtualhubs/VirtualHubsConfigurationTest.java
  data/virtual-hubs/virtual-hubs-json/src/main/java/com/powsybl/openrao/virtualhubs/json/VirtualHubsConfigurationDeserializer.java
  data/virtual-hubs/virtual-hubs-json/src/main/java/com/powsybl/openrao/virtualhubs/json/VirtualHubsConfigurationSerializer.java
  data/virtual-hubs/virtual-hubs-json/src/test/java/com/powsybl/openrao/virtualhubs/json/JsonVirtualHubsConfigurationTest.java
  data/virtual-hubs/virtual-hubs-json/src/test/resources/virtualHubsConfigurationFile.json
  data/virtual-hubs/virtual-hubs-network-assigner/src/main/java/com/powsybl/openrao/virtualhubs/networkextensionbuilder/VirtualHubAssigner.java
  data/virtual-hubs/virtual-hubs-network-assigner/src/test/java/com/powsybl/openrao/virtualhubs/networkextensionbuilder/VirtualHubAssignerTest.java
  data/virtual-hubs/virtual-hubs-xml/src/main/java/com/powsybl/openrao/virtualhubs/xml/VirtualHubsConfigurationImporter.java
  data/virtual-hubs/virtual-hubs-xml/src/test/java/com/powsybl/openrao/virtualhubs/xml/VirtualHubsConfigurationImporterTest.java
  data/virtual-hubs/virtual-hubs-xml/src/test/resources/virtualHubsConfigurationFile.xml
Labels: enhancement, PR: waiting-for-review, next-release

#957 Do not export angle monitoring additional constraints if angle monitoring not run
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweAdditionalConstraintSeriesCreator.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/SweAdditionalConstraintSeriesCreatorTest.java
  data/result-exporter/swe-cne-exporter/src/test/resources/SweCNEDivergentAngleMonitoring_Z01.xml
Labels: bug, next-release

#961 More logical page tree
  docs/castor.md
  docs/castor/applications.md
  docs/castor/linear-problem.md
  docs/castor/monitoring.md
  docs/castor/monitoring/angle-monitoring.md
  docs/castor/monitoring/angle-monitoring/algorithm.md
  docs/castor/monitoring/angle-monitoring/introduction.md
  docs/castor/monitoring/angle-monitoring/java-api.md
  docs/castor/monitoring/angle-monitoring/logs.md
  docs/castor/monitoring/angle-monitoring/result.md
  docs/castor/monitoring/voltage-monitoring.md
  docs/castor/monitoring/voltage-monitoring/algorithm.md
  docs/castor/monitoring/voltage-monitoring/introduction.md
  docs/castor/monitoring/voltage-monitoring/java-api.md
  docs/castor/monitoring/voltage-monitoring/logs.md
  docs/castor/monitoring/voltage-monitoring/result.md
  docs/castor/special-features.md
  docs/glossary.md
  docs/index.md
  docs/input-data.md
  docs/input-data/crac.md
  docs/input-data/glsk.md
  docs/output-data.md
  docs/output-data/core-cne.md
  docs/output-data/rao-logs.md
  docs/output-data/rao-result.md
  docs/output-data/swe-cne.md
  docs/parameters.md
  docs/tutorial.md
Labels: enhancement, documentation

#953 define auto remedial action if time to implement is below threshold
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/CsaProfileRemedialActionsCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/ElementaryActionsHelper.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/parameters/CsaCracCreationParameters.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/parameters/JsonCsaCracCreationParameters.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracCreationTestUtil.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/parameters/JsonCsaCracCreationParametersTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/PstRangeActionCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/parameters/csa-crac-parameters-json-csa-crac-creation-parameters-test.json
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/parameters/csa-crac-parameters-with-region-eic-code.json
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/parameters/csaCracCreationParameters_SPS_0_sec.json
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/parameters/csaCracCreationParameters_SPS_60_sec.json
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/profiles/remedialactions/CSA-92_PST-SPS_with_0_sec_threshold.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/profiles/remedialactions/CSA-92_PST-SPS_with_60_sec_threshold.zip
Labels: enhancement

#926 Update doc for contingencies
  docs/input-data/crac/import.md
  docs/input-data/crac/json.md
  docs/tutorial.md
Labels: PR: waiting-for-review, next-release

#967 Remove ill-defined AExCO combinations
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/CsaProfileCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileSsiTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/FlowCnecCreationTest.java
Labels: bug, PR: waiting-for-review

#966 Add SWE CNE tests for angle values
  tests/src/test/resources/features/epic12_export_improvement/US12_15.feature
  tests/src/test/resources/files/cne/epic12/ExpectedCNE_12_15_5.xml
  tests/src/test/resources/files/crac/epic12/CIM_12_15_5.xml
  tests/src/test/resources/files/raoresults/epic12/RaoResult_12_15_5.json
Labels: PR: waiting-for-review, tests

#970 CSA import bugs on RemedialActionGroups, RAxAE instants coherence and onConstraint usage rules
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/CsaProfileRemedialActionsCreator.java
Labels: bug

#974 [CSA] [Import] Harmonize import errors with throw and try-catch
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/AbstractCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/AngleCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/CsaProfileCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/FlowCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/VoltageCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/contingency/CsaProfileContingencyCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/CsaProfileRemedialActionsCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/ElementaryActionsHelper.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/PstRangeActionCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileSsiTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/FlowCnecCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/contingencies/ContingenciesCreationTest.java
Labels: PR: waiting-for-review, cleaning

#969 Change test 12.15.6
  tests/src/test/resources/features/epic12_export_improvement/US12_15.feature
  tests/src/test/resources/files/cne/epic12/ExpectedCNE_12_15_6.xml
  tests/src/test/resources/files/raoresults/epic12/RaoResult_12_15_6.json
Labels: PR: waiting-for-review, tests

#971 Fix memory leak due to leaves sometimes keeping reference to the network
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/SearchTree.java
Labels: bug, PR: waiting-for-info-reviewer, cleaning

#977 Change crac validator
  data/crac/crac-util/src/main/java/com/powsybl/openrao/data/cracutil/CracValidator.java
  data/crac/crac-util/src/test/java/com/powsybl/openrao/data/cracutil/CracValidatorTest.java
Labels: PR: waiting-for-review, cleaning, next-release

#978 Correct cim.md
  docs/input-data/crac/cim.md
Labels: documentation

#959 [CSA Profiles] [Import] Reliability margin for FlowCNECs
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileConstants.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/CsaProfileCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/FlowCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/resources/csa_profile.sparql
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/FlowCnecCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/profiles/cnecs/FlowCNECsWithReducedLimits.zip
Labels: feature, PR: waiting-for-review

#979 Accelerate state tree init
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/AbstractRemedialAction.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/RemedialActionTest.java
Labels: PR: waiting-for-review, cleaning

#976 Filter ct from sensi
  sensitivity-analysis/pom.xml
  sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/RangeActionSensitivityProvider.java
  sensitivity-analysis/src/test/java/com/powsybl/openrao/sensitivityanalysis/RangeActionSensitivityProviderTest.java
Labels: bug, PR: waiting-for-review

#985 Remove CRAC utils classes that are not used (CracCleaningFeature and UcteNodeMatchingRule)
  data/crac/crac-util/src/main/java/com/powsybl/openrao/data/cracutil/CracCleaningFeature.java
  data/crac/crac-util/src/main/java/com/powsybl/openrao/data/cracutil/UcteNodeMatchingRule.java
Labels: PR: waiting-for-review, cleaning

#972 [CSA] [Import] Reorder usage rules definition
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracUtils.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/CsaProfileCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/contingency/CsaProfileContingencyCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/AssociationStatus.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/CsaProfileRemedialActionsCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/ElementaryActionsHelper.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/NetworkActionCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/OnConstraintUsageRuleHelper.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/OnContingencyStateUsageRuleHelper.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/PstRangeActionCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/resources/csa_profile.sparql
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracCreationTestUtil.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracUtilsTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/AngleCnecCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/FlowCnecCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/VoltageCnecCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/AutoRemedialActionTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/GroupRemedialActionTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/OnConstraintUsageRuleHelperTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/OnContingencyStateUsageRuleHelperTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/RemedialActionCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/profiles/remedialactions/AutoRemedialActions.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/profiles/remedialactions/UsageRules.zip
Labels: bug, PR: waiting-for-review, cleaning
