Repository powsybl/powsybl-open-rao, pull requests merged in 2024-05, with the labels that each got.

#990 Mutualize code for onConstraint usage rules
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/AbstractOnConstraintUsageRule.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/OnAngleConstraintImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/OnFlowConstraintImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/OnVoltageConstraintImpl.java
Labels: PR: waiting-for-review, cleaning

#989 Fix getUsageMethod bug introduced by #979
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/AbstractRemedialAction.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/RemedialActionTest.java
Labels: bug, PR: waiting-for-review

#987 Add optional contingency to OnFlowConstraintInCountry
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/JsonSerializationConstants.java
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/deserializers/OnFlowConstraintInCountryArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/serializers/OnFlowConstraintInCountrySerializer.java
  data/crac-io/crac-io-json/src/test/java/com/powsybl/openrao/data/craciojson/CracImportExportTest.java
  data/crac-io/crac-io-json/src/test/java/com/powsybl/openrao/data/craciojson/JsonRetrocompatibilityTest.java
  data/crac-io/crac-io-json/src/test/resources/retrocompatibility/v2/crac-v2.2.json
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/usagerule/OnFlowConstraintInCountry.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/usagerule/OnFlowConstraintInCountryAdder.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/usagerule/UsageRule.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/AbstractRemedialAction.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/OnFlowConstraintInCountryAdderImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/OnFlowConstraintInCountryImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/AbsRemedialActionTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/OnFlowConstraintInCountryAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/OnFlowConstraintInCountryImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/RemedialActionTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/utils/ExhaustiveCracCreation.java
  data/crac/crac-util/src/main/java/com/powsybl/openrao/data/cracutil/CracValidator.java
  docs/input-data/crac/json.md
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/RaoUtilTest.java
  tests/src/test/resources/features/extra_features/US_UR_1_usage_rules.feature
  tests/src/test/resources/files/crac/extra_features/Crac_UR_1_1.json
  tests/src/test/resources/files/crac/extra_features/Crac_UR_1_2.json
Labels: feature, PR: waiting-for-review, next-release

#994 Second preventive RAO: fail if one sensitivity fails
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
Labels: bug, PR: waiting-for-review

#998 Run angle monitoring with automatically generated proportional GLSK
  monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/AbstractRedispatchAction.java
  monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/AngleMonitoring.java
  monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/RedispatchAction.java
  monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/RedispatchActionWithAutoGlsk.java
  monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/RedispatchActionWithGlskPoint.java
  monitoring/angle-monitoring/src/test/java/com/powsybl/openrao/monitoring/anglemonitoring/AngleMonitoringTest.java
  monitoring/angle-monitoring/src/test/java/com/powsybl/openrao/monitoring/anglemonitoring/RedispatchActionWithAutoGlskTest.java
  monitoring/angle-monitoring/src/test/resources/TestCase_with_swe_countries.xiidm
  tests/src/test/java/com/powsybl/openrao/tests/steps/AngleMonitoringSteps.java
Labels: feature, PR: waiting-for-review, next-release

#1001 Add in Country with contingency on flow constraint usage rule
  data/crac-creation/crac-creator-cim/src/main/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/remedialaction/RemedialActionSeriesCreator.java
  data/crac-creation/crac-creator-cim/src/test/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/CimCracCreatorTest.java
  data/crac-creation/crac-creator-cim/src/test/resources/cracs/CIM_21_5_2.xml
  docs/input-data/crac/cim.md
  tests/src/test/java/com/powsybl/openrao/tests/steps/CracImportSteps.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic21_cim_crac_swe_d2/US21_6.feature
  tests/src/test/resources/files/crac/epic21/CIM_21_6_2.xml
Labels: bug, PR: waiting-for-review, next-release

#995 Better explanation of automaton simulator
  docs/castor/rao-steps.md
Labels: documentation

#1004 Fix OnFlowConstraintInCountry with contingency interpretation in RAO
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/OnFlowConstraintInCountryImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/OnFlowConstraintInCountryImplTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/RaoUtilTest.java
Labels: bug, PR: waiting-for-review, next-release

#1008 Fix sonar issue
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/serializers/OnFlowConstraintInCountrySerializer.java
Labels: PR: ready-to-be-merged, cleaning

#1005 Fix bug injection setpoint shunt compensator can be applied
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/InjectionSetpointImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/InjectionSetpointImplTest.java
Labels: bug

#1007 Update angle monitoring doc
  docs/castor/monitoring/angle-monitoring/introduction.md
  docs/castor/monitoring/angle-monitoring/java-api.md
Labels: PR: waiting-for-review, next-release, documentation

#904 Decrease remedial action usage limits among consecutive instants of the same kind
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/RaUsageLimits.java
  docs/input-data/crac/json.md
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/parameters/SearchTreeParameters.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimizationTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/parameters/SearchTreeParametersTest.java
  ra-optimisation/search-tree-rao/src/test/resources/crac/small-crac-ra-limits-per-instant-3-tsos.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/small-crac-ra-limits-per-instant.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/small-crac-with-comprehensive-usage-limits.json
  ra-optimisation/search-tree-rao/src/test/resources/network/12Nodes_4ParallelLines.uct
Labels: feature, PR: waiting-for-review

#968 Add readmes
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/_static/developer-resources/.editorconfig
  docs/_static/developer-resources/Eclipse.xml
  docs/_static/developer-resources/Intellij.xml
  docs/index.md
  docs/tutorial.md
  tests/README.md
Labels: PR: waiting-for-review, documentation

#963 Harmonize bloomer filters
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/AlreadyAppliedNetworkActionsFilter.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/AlreadyTestedCombinationsFilter.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/FarFromMostLimitingElementFilter.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/MaximumNumberOfRemedialActionPerTsoFilter.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/MaximumNumberOfRemedialActionsFilter.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/MaximumNumberOfTsosFilter.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/NetworkActionCombinationFilter.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/SearchTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/SearchTreeBloomer.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/AlreadyAppliedNetworkActionsFilterTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/AlreadyTestedCombinationsFilterTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/FarFromMostLimitingElementFilterTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/MaximumNumberOfRemedialActionPerTsoFilterTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/MaximumNumberOfRemedialActionsFilterTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/MaximumNumberOfTsosFilterTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/NetworkActionCombinationsUtils.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/SearchTreeBloomerTest.java
Labels: PR: waiting-for-review, cleaning

#1012 Log project version and git commit hash at the start of the RAO
  docs/output-data/rao-logs/example.md
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/Rao.java
Labels: feature, PR: waiting-for-review

#1018 Fix RA group importer
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/CsaProfileRemedialActionsCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/GroupRemedialActionTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/profiles/remedialactions/RemedialActionGroupFromInvalidTopologyAction.zip
Labels: bug, PR: waiting-for-review, next-release

#1014 Filter NaN flows from MIP
  docs/castor/linear-problem/core-problem-filler.md
  docs/castor/linear-problem/max-loop-flow-filler.md
  docs/castor/linear-problem/max-min-margin-filler.md
  docs/castor/linear-problem/max-min-relative-margin-filler.md
  docs/castor/linear-problem/mnec-filler.md
  docs/castor/linear-problem/ra-usage-limits-filler.md
  docs/castor/linear-problem/unoptimized-cnec-filler-cra.md
  docs/castor/linear-problem/unoptimized-cnec-filler-pst.md
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/RaoUtil.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/ObjectiveFunction.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/FillersUtil.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemBuilder.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/OpenRaoMPConstraint.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/OpenRaoMPObjective.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/OpenRaoMPSolver.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/OpenRaoMPVariable.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/RaoUtilTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/ObjectiveFunctionTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/LinearProblemBuilderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/LinearProblemTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/AbstractFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/FillersUtilTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFillerMarginDecreaseRuleTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFillerPstLimitationRuleTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/MPConstraintMock.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/MPObjectiveMock.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/MPVariableMock.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/OpenRaoMPSolver.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/OpenRaoMPSolverTest.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic12_export_improvement/US12_15.feature
Labels: bug, PR: waiting-for-review, next-release

#1010 Fix CIM Angle CNEC creation
  data/crac-creation/crac-creator-cim/src/main/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/cnec/AdditionalConstraintSeriesCreator.java
  data/crac-creation/crac-creator-cim/src/test/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/CimCracCreatorTest.java
  data/crac-creation/crac-creator-cim/src/test/resources/cracs/CIM_21_7_1.xml
  docs/input-data/crac/cim.md
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic21_cim_crac_swe_d2/US21_7.feature
Labels: bug, next-release

#981 Change bad keyword in StaticPropertyRange query
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/constants/CsaProfileConstants.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/constants/OverridingObjectsFields.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/nc/StaticPropertyRange.java
  data/crac-creation/crac-creator-csa-profiles/src/main/resources/csa_profile.sparql
Labels: PR: ready-to-be-merged

#1013 Add RELATIVE_TO_PREVIOUS_TIMESTEP Range Type
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/JsonSerializationConstants.java
  data/crac-io/crac-io-json/src/test/java/com/powsybl/openrao/data/craciojson/CracImportExportTest.java
  data/crac-io/crac-io-json/src/test/java/com/powsybl/openrao/data/craciojson/JsonRetrocompatibilityTest.java
  data/crac-io/crac-io-json/src/test/resources/retrocompatibility/v2/crac-v2.3.json
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/range/RangeType.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/PstRangeActionImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/utils/ExhaustiveCracCreation.java
  docs/input-data/crac/json.md
Labels: PR: ready-to-be-merged

#1017 Add a border attribute to cnecs
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/JsonSerializationConstants.java
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/deserializers/AngleCnecArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/deserializers/FlowCnecArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/deserializers/VoltageCnecArrayDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/serializers/AngleCnecSerializer.java
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/serializers/FlowCnecSerializer.java
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/craciojson/serializers/VoltageCnecSerializer.java
  data/crac-io/crac-io-json/src/test/java/com/powsybl/openrao/data/craciojson/JsonRetrocompatibilityTest.java
  data/crac-io/crac-io-json/src/test/resources/retrocompatibility/v2/crac-v2.3.json
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/cnec/Cnec.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/cnec/CnecAdder.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/AbstractBranchCnec.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/AbstractCnec.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/AbstractCnecAdderImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/AngleCnecAdderImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/AngleCnecImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/FlowCnecAdderImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/FlowCnecImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/VoltageCnecAdderImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/VoltageCnecImpl.java
  docs/input-data/crac/json.md
Labels: feature, PR: waiting-for-review

#924 feat(optimization): re-optimize some PSTs in second preventive
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/AutomatonSimulator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimizationTest.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic13_curative/US13_5.feature
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic15_specific_network_elements/epic15_11/US15_11_4.feature
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic15_specific_network_elements/epic15_11/US15_11_5.feature
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic20_advanced_search_tree/US20_1.feature
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic20_advanced_search_tree/US20_2.feature
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic20_advanced_search_tree/US20_4.feature
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic20_advanced_search_tree/US20_5.feature
  tests/src/test/resources/files/crac/epic20/second_preventive_ls_1_2.json
  tests/src/test/resources/files/crac/epic20/second_preventive_ls_1_3.json
  tests/src/test/resources/files/crac/epic20/second_preventive_ls_1_4.json
  tests/src/test/resources/files/crac/epic20/second_preventive_ls_1_5.json
  tests/src/test/resources/files/crac/epic20/second_preventive_ls_1_6.json
  tests/src/test/resources/files/crac/epic20/second_preventive_ls_1_7.json
  tests/src/test/resources/files/crac/epic20/second_preventive_ls_1_8.json
Labels: feature, PR: waiting-for-review
