Repository powsybl/powsybl-open-rao, pull requests merged in 2024-06, with the labels that each got.

#912 Network action compatibility filter
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/networkaction/ElementaryAction.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/networkaction/InjectionSetpoint.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/networkaction/NetworkAction.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/networkaction/PstSetpoint.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/networkaction/SwitchPair.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/networkaction/TopologicalAction.java
  data/crac/crac-api/src/test/java/com/powsybl/openrao/data/cracapi/ElementaryActionCompatibilityTest.java
  data/crac/crac-api/src/test/java/com/powsybl/openrao/data/cracapi/NetworkActionTest.java
  data/crac/crac-api/src/test/java/com/powsybl/openrao/data/cracapi/NetworkActionUtils.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/InjectionSetpointImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/NetworkActionImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/PstSetpointImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/SwitchPairImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/TopologicalActionImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/utils/CommonCracCreation.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/ElementaryActionsCompatibilityFilter.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/SearchTreeBloomer.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/ElementaryActionsCompatibilityFilterTest.java
Labels: PR: waiting-for-correction, PR: waiting-for-info-reviewer

#1044 Doc: link to new parent website
  docs/conf.py
Labels: PR: waiting-for-review, documentation

#905 Check physical parameters in RaoResult's isSecure
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/Instant.java
  data/crac/crac-api/src/test/java/com/powsybl/openrao/data/cracapi/InstantTest.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/InstantImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/InstantImplTest.java
  data/rao-result/rao-result-api/src/main/java/com/powsybl/openrao/data/raoresultapi/RaoResult.java
  data/rao-result/rao-result-impl/src/main/java/com/powsybl/openrao/data/raoresultimpl/RaoResultImpl.java
  data/rao-result/rao-result-impl/src/test/java/com/powsybl/openrao/data/raoresultimpl/RaoResultImplTest.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCne.java
  monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/RaoResultWithAngleMonitoring.java
  monitoring/angle-monitoring/src/test/java/com/powsybl/openrao/monitoring/anglemonitoring/RaoResultWithAngleMonitoringTest.java
  monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/RaoResultWithVoltageMonitoring.java
  monitoring/voltage-monitoring/src/test/java/com/powsybl/openrao/monitoring/voltagemonitoring/RaoResultWithVoltageMonitoringTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/AbstractFlowRaoResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/OneStateOnlyRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/UnoptimizedRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/OneStateOnlyRaoResultImplTest.java
Labels: bug, PR: waiting-for-review, next-release

#1039 [CSA] Fixes for Angle and Voltage CNECs import
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/AngleCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/VoltageCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracCreationTestUtil.java
Labels: bug, PR: waiting-for-review, cleaning

#1016 Allow multi-curative in second preventive optimisation
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/Crac.java
  loopflow-computation/src/main/java/com/powsybl/openrao/loopflowcomputation/LoopFlowResult.java
  loopflow-computation/src/test/java/com/powsybl/openrao/loopflowcomputation/LoopFlowResultTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/adapter/BranchResultAdapterImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/api/FlowResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/AutomatonPerimeterResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/CurativeWithSecondPraoResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/EmptyFlowResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/FlowResultFromMapImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/FlowResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/IteratingLinearOptimizationResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PerimeterResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PrePerimeterSensitivityResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/SkippedOptimizationResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimizationTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/PrePerimeterSensitivityAnalysisTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/adapter/FlowResultAdapterImplTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/CurativeWithSecondPraoResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/EmptyFlowResultImplTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/FlowResultFromMapImplTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/FlowResultImplTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImplTest.java
  sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityResult.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic91_rao_enhancements/US91_12.feature
  tests/src/test/resources/files/configurations/epic91/RaoParameters_case_91_12_secure_2PRAO.json
  tests/src/test/resources/files/crac/epic91/crac_91_12_16.json
  tests/src/test/resources/files/crac/epic91/crac_91_12_17.json
  tests/src/test/resources/files/crac/epic91/crac_91_12_18.json
  tests/src/test/resources/files/crac/epic91/crac_91_12_19.json
  tests/src/test/resources/files/crac/epic91/crac_91_12_20.json
Labels: feature, PR: waiting-for-review

#1068 fix bug on 2P Global Optimization with PST modeled as `APPROXIMATED_INTEGERS`
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemBuilder.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic19_specific_rao_parameters/US19_11.feature
  tests/src/test/resources/files/cases/epic19/small-network-2P.uct
  tests/src/test/resources/files/configurations/epic19/RaoParameters_19_11_9.json
  tests/src/test/resources/files/configurations/epic19/RaoParameters_19_11_9_bis.json
  tests/src/test/resources/files/crac/epic19/SL_ep19us11case9.json
Labels: bug, MIP
