Repository powsybl/powsybl-open-rao, pull requests merged in 2024-02, with the labels that each got.

#883 Test for SSI profile import
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/CsaProfileCrac.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileConstants.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/CsaProfileCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/CsaProfileRemedialActionsCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/NetworkActionCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/resources/csa_profile.sparql
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracCreationTestUtil.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileSsiTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/InjectionSetPointActionCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/PstRangeActionCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/TopologicalActionCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/TestCase16NodesWithShuntCompensator.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/csa-23/CSA_23_1_ValidProfiles.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-10_ShuntCompensatorModification.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-11_ElementaryActions.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-12_ContingencyWithRemedialAction.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-13_AngleCNEC.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-14_VoltageAngleLimit.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-15_AssessedElementWithContingency.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-16_AssessedElementWithRemedialAction.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-1_Contingency.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-2_RemedialAction.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-3_ChangeTopologicalActionType.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-4_RestrictPSTActionRange.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-5_ChangeRotatingMachineActionSetpoint.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-6_TopologyAction.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-7_RotatingMachineAction.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-8_ActivateTapPositionAction.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/ssi/SSI-9_DeactivateTapPositionAction.zip
Labels: PR: ready-to-be-merged

#877 Multiple curative states
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/Crac.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/Instant.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/CracImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/InstantImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/InstantImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/utils/CommonCracCreation.java
  data/rao-result/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresultjson/serializers/AngleCnecResultArraySerializer.java
  data/rao-result/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresultjson/serializers/ComputationStatusMapSerializer.java
  data/rao-result/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresultjson/serializers/FlowCnecResultArraySerializer.java
  data/rao-result/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresultjson/serializers/VoltageCnecResultArraySerializer.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/AutomatonSimulator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/BasecaseScenario.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorOneStateOnly.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/ContingencyScenario.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/Perimeter.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/StateTree.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/RaoLogger.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/optimizationperimeters/PreventiveOptimizationPerimeter.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/AutomatonSimulatorTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/BasecaseScenarioTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimizationTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/ContingencyScenarioTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/PerimeterTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/StateTreeTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/RaoLoggerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/optimizationperimeters/PreventiveOptimizationPerimeterTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImplTest.java
Labels: PR: waiting-for-review

#889 csa profiles groups and dependencies
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/CsaProfileCrac.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileConstants.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/CsaProfileRemedialActionsCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/ElementaryActionsHelper.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/NetworkActionCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/PstRangeActionCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/resources/csa_profile.sparql
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileSsiTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/GroupRemedialActionTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/remedialaction/PstRangeActionCreationTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/CSA_80.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/RaWithMultipleTapPositions.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/RemedialActionGroups_HVDC.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/SSI-19_RemedialActionDependency.zip
  data/crac-creation/crac-creator-csa-profiles/src/test/resources/SSI-20_RemedialActionGroup.zip
Labels: PR: waiting-for-review

#902 Fix multi position period for timeseries in Crac import
  data/crac-creation/crac-creator-cim/src/main/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/CimConstants.java
  data/crac-creation/crac-creator-cim/src/main/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/CimCracUtils.java
  data/crac-creation/crac-creator-cim/src/main/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/PointPositionComparator.java
  data/crac-creation/crac-creator-cim/src/main/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/cnec/MonitoredSeriesCreator.java
  data/crac-creation/crac-creator-cim/src/main/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/contingency/CimContingencyCreator.java
  data/crac-creation/crac-creator-cim/src/main/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/remedialaction/RemedialActionSeriesCreator.java
  data/crac-creation/crac-creator-cim/src/test/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/CimCracCreatorTest.java
  data/crac-creation/crac-creator-cim/src/test/resources/cracs/CIM_21_1_1_multi_period.xml
Labels: bug

#885 Fix monitoring module to avoid class cast exception in case of RangeAction being selected
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweAdditionalConstraintSeriesCreator.java
  monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/AngleMonitoring.java
  monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/AngleMonitoringResult.java
  monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/RaoResultWithAngleMonitoring.java
  monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/json/AngleMonitoringResultDeserializer.java
  monitoring/angle-monitoring/src/test/java/com/powsybl/openrao/monitoring/anglemonitoring/json/JsonAngleMonitoringResultTest.java
  monitoring/monitoring-commons/src/main/java/com/powsybl/openrao/monitoring/monitoringcommon/json/MonitoringCommonDeserializer.java
  monitoring/monitoring-commons/src/main/java/com/powsybl/openrao/monitoring/monitoringcommon/json/MonitoringCommonSerializer.java
  monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/RaoResultWithVoltageMonitoring.java
  monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/VoltageMonitoring.java
  monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/VoltageMonitoringResult.java
  monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/json/VoltageMonitoringResultDeserializer.java
Labels: bug
