Repository powsybl/powsybl-open-rao, pull requests merged in 2024-08, with the labels that each got.

#1099 Fix raoResult.isSecure(ANGLE) and raoResult.isSecure(VOLTAGE)
  monitoring/angle-monitoring/src/main/java/com/powsybl/openrao/monitoring/anglemonitoring/RaoResultWithAngleMonitoring.java
  monitoring/angle-monitoring/src/test/java/com/powsybl/openrao/monitoring/anglemonitoring/RaoResultWithAngleMonitoringTest.java
  monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/RaoResultWithVoltageMonitoring.java
  monitoring/voltage-monitoring/src/test/java/com/powsybl/openrao/monitoring/voltagemonitoring/RaoResultWithVoltageMonitoringTest.java
Labels: bug, PR: waiting-for-review, next-release

#1102 Indicate reason to failed RAO
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/Castor.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorOneStateOnly.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/FailedRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/FailedRaoResultImplTest.java
Labels: feature, PR: waiting-for-review, next-release

#1107 [FbConstraintDocument] Support new schema versions
  data/crac-io/crac-io-fb-constraint/src/main/java/com/powsybl/openrao/data/cracio/fbconstraint/FbConstraintImporter.java
  data/crac-io/crac-io-fb-constraint/src/test/resources/merged_cb/MNEC_test.xml
  data/crac-io/crac-io-fb-constraint/src/test/resources/merged_cb/corrupted.xml
  data/crac-io/crac-io-fb-constraint/src/test/resources/merged_cb/schema_v99.xml
  data/crac-io/crac-io-fb-constraint/src/test/resources/merged_cb/transformers.xml
Labels: PR: waiting-for-review, next-release

#1113 update xsd for core cc
  data/crac-io/crac-io-fb-constraint/src/main/java/com/powsybl/openrao/data/cracio/fbconstraint/FbConstraintImporter.java
  data/crac-io/crac-io-fb-constraint/src/main/resources/xjb/binding.xjb
  data/crac-io/crac-io-fb-constraint/src/main/resources/xsd/flowbasedconstraintdocument-23.xsd
  data/crac-io/crac-io-fb-constraint/src/main/resources/xsd/validation/flowbasedconstraintdocument-18.xsd
Labels: PR: waiting-for-review

#1118 Fix concurrent exceptions due to Map in FlowResultImpl
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/FlowResultImpl.java
Labels: PR: waiting-for-review

#1115 SWE CNE export Xnode ID for tie-lines
  data/crac-io/crac-io-cim/src/main/java/com/powsybl/openrao/data/cracio/cim/craccreator/MonitoredSeriesCreator.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCneUtil.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweMonitoredSeriesCreator.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/SweMonitoredSeriesCreatorTest.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/TieLineTest.java
  data/result-exporter/swe-cne-exporter/src/test/resources/SweTestCaseWith12NodesAndXnodes.uct
  tests/src/test/java/com/powsybl/openrao/tests/steps/CneExportSteps.java
  tests/src/test/java/com/powsybl/openrao/tests/utils/CneHelper.java
Labels: bug, PR: waiting-for-review, next-release
