Repository powsybl/powsybl-open-rao, pull requests merged in 2024-07, with the labels that each got.

#1072 fix broken links in doc
  docs/README.md
  docs/castor.md
  docs/castor/applications.md
  docs/castor/linear-problem.md
  docs/castor/linear-problem/continuous-range-action-group-filler.md
  docs/castor/linear-problem/core-problem-filler.md
  docs/castor/linear-problem/discrete-pst-group-filler.md
  docs/castor/linear-problem/discrete-pst-tap-filler.md
  docs/castor/linear-problem/max-loop-flow-filler.md
  docs/castor/linear-problem/max-min-margin-filler.md
  docs/castor/linear-problem/max-min-relative-margin-filler.md
  docs/castor/linear-problem/mnec-filler.md
  docs/castor/linear-problem/ra-usage-limits-filler.md
  docs/castor/linear-problem/unoptimized-cnec-filler-cra.md
  docs/castor/monitoring/angle-monitoring/algorithm.md
  docs/castor/monitoring/angle-monitoring/java-api.md
  docs/castor/monitoring/angle-monitoring/result.md
  docs/castor/monitoring/voltage-monitoring/algorithm.md
  docs/castor/monitoring/voltage-monitoring/java-api.md
  docs/castor/monitoring/voltage-monitoring/result.md
  docs/castor/performance.md
  docs/castor/rao-steps.md
  docs/castor/special-features/do-not-optimize-specific-cnecs.md
  docs/castor/special-features/loop-flows.md
  docs/input-data.md
  docs/input-data/crac.md
  docs/input-data/crac/creation-context.md
  docs/input-data/crac/creation-parameters.md
  docs/input-data/crac/cse.md
  docs/input-data/crac/json.md
  docs/output-data.md
  docs/output-data/core-cne/cnec-results.md
  docs/output-data/core-cne/header.md
  docs/output-data/core-cne/introduction.md
  docs/output-data/core-cne/java-api.md
  docs/output-data/rao-logs.md
  docs/output-data/rao-logs/example.md
  docs/output-data/rao-result.md
  docs/output-data/rao-result/angle-cnecs.md
  docs/output-data/rao-result/steps.md
  docs/output-data/rao-result/voltage-cnecs.md
  docs/output-data/swe-cne/cnec-results.md
  docs/output-data/swe-cne/header.md
  docs/output-data/swe-cne/introduction.md
  docs/output-data/swe-cne/java-api.md
  docs/output-data/swe-cne/ra-results.md
  docs/parameters.md
  docs/tutorial.md
Labels: PR: waiting-for-review

#1002 CSA-Profiles fixes
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/AbstractCnecCreator.java
  data/crac-creation/crac-creator-csa-profiles/src/main/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/cnec/AngleCnecCreator.java
Labels: bug, PR: waiting-for-review

#1076 Replace unknown status by failure status in voltageMonitoringResult
  docs/castor/monitoring/voltage-monitoring/algorithm.md
  monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/RaoResultWithVoltageMonitoring.java
  monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/VoltageMonitoring.java
  monitoring/voltage-monitoring/src/main/java/com/powsybl/openrao/monitoring/voltagemonitoring/VoltageMonitoringResult.java
  monitoring/voltage-monitoring/src/test/java/com/powsybl/openrao/monitoring/voltagemonitoring/VoltageMonitoringTest.java
  monitoring/voltage-monitoring/src/test/java/com/powsybl/openrao/monitoring/voltagemonitoring/json/JsonVoltageMonitoringResultTest.java
  monitoring/voltage-monitoring/src/test/resources/result.json
  monitoring/voltage-monitoring/src/test/resources/voltage-monitoring-result.json
Labels: next-release

#1070 make relative range more precise
  docs/castor/linear-problem/core-problem-filler.md
  docs/castor/linear-problem/discrete-pst-tap-filler.md
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/BestTapFinder.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizer.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemBuilder.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/LinearProblemResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/RangeActionActivationResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/BestTapFinderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/FillersUtilTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFillerMarginDecreaseRuleTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/RangeActionActivationResultImplTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/LeafTest.java
Labels: PR: waiting-for-review

#1063 Resolve some TODOs
  data/crac-creation/crac-creator-cim/src/main/java/com/powsybl/openrao/data/craccreation/creator/cim/craccreator/NetworkActionCreator.java
  data/crac-creation/crac-creator-cse/src/main/java/com/powsybl/openrao/data/craccreation/creator/cse/CseCracCreator.java
  data/crac-creation/crac-creator-cse/src/test/java/com/powsybl/openrao/data/craccreation/creator/cse/CseCracCreatorWithMneTest.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/CracFactory.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/ContingencyAdderImpl.java
  data/crac/crac-loopflow-extension/src/main/java/com/powsybl/openrao/data/cracloopflowextension/JsonCnecLoopFlowExtensionSerializer.java
  data/crac/crac-loopflow-extension/src/main/java/com/powsybl/openrao/data/cracloopflowextension/LoopFlowThresholdAdderImpl.java
  data/crac/crac-loopflow-extension/src/main/java/com/powsybl/openrao/data/cracloopflowextension/LoopFlowThresholdImpl.java
  data/crac/crac-loopflow-extension/src/main/java/com/powsybl/openrao/data/cracloopflowextension/LoopFlowThresholdUtils.java
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/parameters/LoadFlowAndSensitivityParameters.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/RaoTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/OneStateOnlyRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PerimeterResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/SearchTree.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimizationTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/ToolProviderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/AutomatonPerimeterResultImplTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/OneStateOnlyRaoResultImplTest.java
Labels: PR: waiting-for-review

#1045 Add HVDC tests for AC emulation mode
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic15_specific_network_elements/US15_17.feature
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic15_specific_network_elements/epic15_12/US15_12_5.feature
  tests/src/test/resources/files/cases/epic15/TestCase16NodesWithHvdcAcEmulation_HvdcCnec.xiidm
  tests/src/test/resources/files/configurations/epic15/RaoParameters_ep15us17case10.json
  tests/src/test/resources/files/configurations/epic15/RaoParameters_ep15us17case11.json
  tests/src/test/resources/files/configurations/epic15/RaoParameters_ep15us17case12.json
  tests/src/test/resources/files/crac/epic15/jsonCrac_ep15us17case10.json
  tests/src/test/resources/files/crac/epic15/jsonCrac_ep15us17case11.json
  tests/src/test/resources/files/crac/epic15/jsonCrac_ep15us17case12.json
Labels: PR: waiting-for-review, tests

#1079 enable back preventive factors after sensi ends in 2P
  sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/AbstractSimpleSensitivityProvider.java
  sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/CnecSensitivityProvider.java
  sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/MultipleSensitivityProvider.java
  sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityAdapter.java
  sensitivity-analysis/src/test/java/com/powsybl/openrao/sensitivityanalysis/RangeActionSensitivityProviderTest.java
Labels: bug, next-release

#1086 More robust MIP + OR-Tools bump
  pom.xml
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/FillersUtil.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/OpenRaoMPSolver.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/LinearProblemTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/AbstractFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/FillersUtilTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFillerMarginDecreaseRuleTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/OpenRaoMPSolverTest.java
  tests/src/test/java/com/powsybl/openrao/tests/RunCucumberTest.java
  tests/src/test/java/com/powsybl/openrao/tests/steps/CneExportSteps.java
  tests/src/test/java/com/powsybl/openrao/tests/utils/Helpers.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic19_specific_rao_parameters/US19_11.feature
Labels: bug, PR: waiting-for-review, next-release, MIP

#1078 Fix OFCC triggered after any outage
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/AutomatonSimulator.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic16_specific_usage_rules/US16_5.feature
  tests/src/test/resources/files/cases/epic16/12Nodes3ParallelLines.uct
  tests/src/test/resources/files/cases/epic16/12Nodes4ParallelLines.uct
  tests/src/test/resources/files/crac/epic16/crac_16_5_14.json
  tests/src/test/resources/files/crac/epic16/crac_16_5_15.json
Labels: bug, PR: waiting-for-review, next-release

#1090 fix(2P): rewrite MIP constraint to respect relative range limits
  docs/castor/linear-problem/discrete-pst-tap-filler.md
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic19_specific_rao_parameters/US19_11.feature
Labels: bug, PR: waiting-for-review, next-release

#1093 MIP bug fixes
  docs/castor/linear-problem/discrete-pst-tap-filler.md
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic19_specific_rao_parameters/US19_11.feature
Labels: bug, MIP

#1032 Replace rao range action apply by core action modification
  data/crac/crac-impl/pom.xml
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/HvdcRangeActionImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/InjectionRangeActionImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/cracimpl/PstRangeActionImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/cracimpl/PstRangeActionImplTest.java
Labels: PR: waiting-for-correction, next-release

#1097 FbConstraintImporter : remove unused flowBasedDocumentVersion variable in importNativeCrac method
  data/crac-creation/crac-creator-fb-constraint/src/main/java/com/powsybl/openrao/data/craccreation/creator/fbconstraint/FbConstraintImporter.java
Labels: cleaning
