Repository powsybl/powsybl-open-rao, pull requests merged in 2024-01, with the labels that each got.

#870 Fix divergence case
  data/rao-result/rao-result-api/src/main/java/com/powsybl/openrao/data/raoresultapi/OptimizationStepsExecuted.java
  data/rao-result/rao-result-api/src/test/java/com/powsybl/openrao/data/raoresultapi/OptimizationStepsExecutedTest.java
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/parameters/LoadFlowAndSensitivityParameters.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/parameters/RaoParametersConsistencyTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/SensitivityFailureOvercostEvaluator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/SkippedOptimizationResultImpl.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/SkippedOptimizationResultImplTest.java
Labels: PR: waiting-for-review

#874 Fix second preventive scenario
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
Labels: bug, PR: waiting-for-review

#878 Update powsybl core to 6.2.0
  data/crac-creation/crac-creation-util/src/test/java/com/powsybl/openrao/data/craccreation/util/cgmes/CgmesBranchHelperTest.java
  data/crac-creation/crac-creator-csa-profiles/src/test/java/com/powsybl/openrao/data/craccreation/creator/csaprofile/craccreator/CsaProfileCracCreationTestUtil.java
  pom.xml
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withExtensions.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withOLFParams.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withPartialExtensions.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withoutExtensions.json
  ra-optimisation/search-tree-rao/src/test/resources/parameters/RaoParameters_2P_v2.json
  ra-optimisation/search-tree-rao/src/test/resources/parameters/RaoParameters_oneIteration_v2.json
Labels: dependencies, PR: WIP
