Repository powsybl/powsybl-open-rao, pull requests merged in 2024-10, with the labels that each got.

#1106 [MIP] Remove ProblemFiller::updateBetweenSensiIteration() method
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemBuilder.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/AbstractFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFillerMarginDecreaseRuleTest.java
Labels: PR: waiting-for-review, cleaning, MIP

#1150 Mutualize RaUsageLimits serializers/deserializers and support `max-elementary-actions-per-tso`
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/cracio/json/deserializers/RaUsageLimitsDeserializer.java
  data/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/cracio/json/serializers/CracSerializer.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/parameters/JsonCracCreationParametersConstants.java
  data/crac/crac-api/src/test/java/com/powsybl/openrao/data/cracapi/parameters/CracCreationParametersJsonTest.java
  data/crac/crac-api/src/test/resources/parameters/crac-creator-parameters-with-ra-limits.json
Labels: feature, PR: waiting-for-review, cleaning

#1157 CNE export no longer uses network
  data/crac/crac-io/crac-io-cim/src/main/java/com/powsybl/openrao/data/cracio/cim/craccreator/CimCracCreationContext.java
  data/crac/crac-io/crac-io-cim/src/main/java/com/powsybl/openrao/data/cracio/cim/craccreator/CimCracCreator.java
  data/crac/crac-io/crac-io-cim/src/test/java/com/powsybl/openrao/data/cracio/cim/craccreator/CimCracCreatorTest.java
  data/result-exporter/cne-exporter-commons/src/main/java/com/powsybl/openrao/data/cneexportercommons/CneHelper.java
  data/result-exporter/core-cne-exporter/src/main/java/com/powsybl/openrao/data/corecneexporter/CoreCne.java
  data/result-exporter/core-cne-exporter/src/main/java/com/powsybl/openrao/data/corecneexporter/CoreCneExporter.java
  data/result-exporter/core-cne-exporter/src/test/java/com/powsybl/openrao/data/corecneexporter/CoreCneCnecsCreatorTest.java
  data/result-exporter/core-cne-exporter/src/test/java/com/powsybl/openrao/data/corecneexporter/CoreCneRemedialActionsCreatorTest.java
  data/result-exporter/core-cne-exporter/src/test/java/com/powsybl/openrao/data/corecneexporter/CoreCneTest.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCne.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCneExporter.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCneHelper.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweMonitoredSeriesCreator.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/SweCneDivergentAngleMonitoringTest.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/SweCneTest.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/SweMonitoredSeriesCreatorTest.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/TieLineTest.java
  docs/output-data/core-cne/java-api.md
  docs/output-data/swe-cne/java-api.md
  tests/src/test/java/com/powsybl/openrao/tests/utils/CneHelper.java
Labels: PR: waiting-for-review, cleaning, breaking-change

#1156 Add CRAC content summary in creation report
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/cracapi/CracCreationReport.java
  data/crac/crac-io/crac-io-cim/src/main/java/com/powsybl/openrao/data/cracio/cim/craccreator/CimCracCreationContext.java
  data/crac/crac-io/crac-io-cim/src/test/java/com/powsybl/openrao/data/cracio/cim/craccreator/CimCracCreatorTest.java
  data/crac/crac-io/crac-io-commons/src/test/java/com/powsybl/openrao/data/cracio/commons/api/CracCreationReportTest.java
  data/crac/crac-io/crac-io-csa-profiles/src/main/java/com/powsybl/openrao/data/cracio/csaprofiles/craccreator/CsaProfileCracCreationContext.java
  data/crac/crac-io/crac-io-cse/src/main/java/com/powsybl/openrao/data/cracio/cse/CseCracCreationContext.java
  data/crac/crac-io/crac-io-cse/src/test/java/com/powsybl/openrao/data/cracio/cse/CseCracCreatorTest.java
  data/crac/crac-io/crac-io-fb-constraint/src/main/java/com/powsybl/openrao/data/cracio/fbconstraint/FbConstraintCreationContext.java
  data/crac/crac-io/crac-io-fb-constraint/src/test/java/com/powsybl/openrao/data/cracio/fbconstraint/FbConstraintCracCreatorTest.java
Labels: feature, PR: waiting-for-review

#1170 Bump powsybl dependencies 6.5.0
  pom.xml
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withExtensions.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withOLFParams.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withPartialExtensions.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withoutExtensions.json
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/AutomatonSimulatorTest.java
Labels: PR: waiting-for-review

#1154 [SWE CNE Export] Round angle and flow values with more decimals in case of violation
  commons/src/main/java/com/powsybl/openrao/commons/MeasurementRounding.java
  commons/src/test/java/com/powsybl/openrao/commons/MeasurementRoundingTest.java
  data/rao-result/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresultjson/serializers/AngleCnecResultArraySerializer.java
  data/rao-result/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresultjson/serializers/CostResultMapSerializer.java
  data/rao-result/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresultjson/serializers/FlowCnecResultArraySerializer.java
  data/rao-result/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresultjson/serializers/VoltageCnecResultArraySerializer.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweAdditionalConstraintSeriesCreator.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCneUtil.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweMonitoredSeriesCreator.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/SweAdditionalConstraintSeriesCreatorTest.java
  monitoring/src/main/java/com/powsybl/openrao/monitoring/results/CnecResult.java
  monitoring/src/test/java/com/powsybl/openrao/monitoring/AngleMonitoringTest.java
  monitoring/src/test/java/com/powsybl/openrao/monitoring/VoltageMonitoringTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/RaoLogger.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimizationTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/RaoLoggerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/LeafTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/SearchTreeTest.java
  tests/src/test/java/com/powsybl/openrao/tests/steps/SearchTreeRaoSteps.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic5_max_margin_stop_criterion/US5_1.feature
  tests/src/test/resources/files/crac/epic5/SL_ep5us1b.json
Labels: feature, PR: waiting-for-review, PR: waiting-for-info-author, next-release

#1169 updated powsybl-parent pom to v19
  pom.xml
Labels: PR: waiting-for-review

#1130 [CSA] No longer read AE.isCombinableWithRemedialAction attribute
  data/crac/crac-io/crac-io-csa-profiles/src/main/java/com/powsybl/openrao/data/cracio/csaprofiles/craccreator/cnec/CsaProfileCnecCreator.java
  data/crac/crac-io/crac-io-csa-profiles/src/main/java/com/powsybl/openrao/data/cracio/csaprofiles/craccreator/cnec/FlowCnecCreator.java
  data/crac/crac-io/crac-io-csa-profiles/src/main/java/com/powsybl/openrao/data/cracio/csaprofiles/craccreator/remedialaction/CsaProfileRemedialActionsCreator.java
  data/crac/crac-io/crac-io-csa-profiles/src/main/java/com/powsybl/openrao/data/cracio/csaprofiles/craccreator/remedialaction/OnConstraintUsageRuleHelper.java
  data/crac/crac-io/crac-io-csa-profiles/src/main/java/com/powsybl/openrao/data/cracio/csaprofiles/nc/AssessedElement.java
  data/crac/crac-io/crac-io-csa-profiles/src/main/resources/csa_profile.sparql
  data/crac/crac-io/crac-io-csa-profiles/src/test/java/com/powsybl/openrao/data/cracio/csaprofiles/craccreator/cnec/AngleCnecCreationTest.java
  data/crac/crac-io/crac-io-csa-profiles/src/test/java/com/powsybl/openrao/data/cracio/csaprofiles/craccreator/cnec/FlowCnecCreationTest.java
  data/crac/crac-io/crac-io-csa-profiles/src/test/java/com/powsybl/openrao/data/cracio/csaprofiles/craccreator/cnec/VoltageCnecCreationTest.java
  data/crac/crac-io/crac-io-csa-profiles/src/test/java/com/powsybl/openrao/data/cracio/csaprofiles/craccreator/remedialaction/OnConstraintUsageRuleHelperTest.java
  data/crac/crac-io/crac-io-csa-profiles/src/test/java/com/powsybl/openrao/data/cracio/csaprofiles/craccreator/remedialaction/RemedialActionCreationTest.java
Labels: PR: waiting-for-review, cleaning, swe-csa

#1158 Unify rao result export
  data/crac/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/cracio/json/JsonCracCreationContext.java
  data/rao-result/rao-result-api/src/main/java/com/powsybl/openrao/data/raoresultapi/RaoResult.java
  data/rao-result/rao-result-api/src/main/java/com/powsybl/openrao/data/raoresultapi/io/Exporter.java
  data/rao-result/rao-result-api/src/test/java/com/powsybl/openrao/data/raoresultapi/MockCracCreationContext.java
  data/rao-result/rao-result-api/src/test/java/com/powsybl/openrao/data/raoresultapi/MockRaoResultExporter.java
  data/rao-result/rao-result-api/src/test/java/com/powsybl/openrao/data/raoresultapi/RaoResultExportTest.java
  data/rao-result/rao-result-json/pom.xml
  data/rao-result/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresultjson/RaoResultJsonExporter.java
  data/rao-result/rao-result-json/src/test/java/com/powsybl/openrao/data/raoresultjson/RaoResultJsonExporterTest.java
  data/rao-result/rao-result-json/src/test/java/com/powsybl/openrao/data/raoresultjson/RaoResultRoundTripTest.java
  data/result-exporter/cne-exporter-commons/src/main/java/com/powsybl/openrao/data/cneexportercommons/CneConstants.java
  data/result-exporter/cne-exporter-commons/src/main/java/com/powsybl/openrao/data/cneexportercommons/CneExporterParameters.java
  data/result-exporter/cne-exporter-commons/src/main/java/com/powsybl/openrao/data/cneexportercommons/CneHelper.java
  data/result-exporter/cne-exporter-commons/src/test/java/com/powsybl/openrao/data/cneexportercommons/CneExporterParametersTest.java
  data/result-exporter/cne-exporter-commons/src/test/java/com/powsybl/openrao/data/cneexportercommons/CneHelperTest.java
  data/result-exporter/core-cne-exporter/src/main/java/com/powsybl/openrao/data/corecneexporter/CoreCne.java
  data/result-exporter/core-cne-exporter/src/main/java/com/powsybl/openrao/data/corecneexporter/CoreCneCnecsCreator.java
  data/result-exporter/core-cne-exporter/src/main/java/com/powsybl/openrao/data/corecneexporter/CoreCneExporter.java
  data/result-exporter/core-cne-exporter/src/main/java/com/powsybl/openrao/data/corecneexporter/CoreCneUtil.java
  data/result-exporter/core-cne-exporter/src/test/java/com/powsybl/openrao/data/corecneexporter/CoreCneCnecsCreatorTest.java
  data/result-exporter/core-cne-exporter/src/test/java/com/powsybl/openrao/data/corecneexporter/CoreCneExporterTest.java
  data/result-exporter/core-cne-exporter/src/test/java/com/powsybl/openrao/data/corecneexporter/CoreCneRemedialActionsCreatorTest.java
  data/result-exporter/core-cne-exporter/src/test/java/com/powsybl/openrao/data/corecneexporter/CoreCneTest.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCne.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCneExporter.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCneHelper.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweCneUtil.java
  data/result-exporter/swe-cne-exporter/src/main/java/com/powsybl/openrao/data/swecneexporter/SweRemedialActionSeriesCreator.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/SweCneDivergentAngleMonitoringTest.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/SweCneExporterTest.java
  data/result-exporter/swe-cne-exporter/src/test/java/com/powsybl/openrao/data/swecneexporter/SweCneTest.java
  docs/output-data/core-cne/introduction.md
  docs/output-data/core-cne/java-api.md
  docs/output-data/rao-result.md
  docs/output-data/swe-cne/introduction.md
  docs/output-data/swe-cne/java-api.md
  tests/src/test/java/com/powsybl/openrao/tests/steps/CneExportSteps.java
  tests/src/test/java/com/powsybl/openrao/tests/utils/CneHelper.java
  tests/src/test/java/com/powsybl/openrao/tests/utils/RaoUtils.java
Labels: PR: waiting-for-review, cleaning, breaking-change
