Repository powsybl/powsybl-open-rao, pull requests merged in 2024-12, with the labels that each got.

#1195 Fix NPE in AutomatonPerimeterResultImpl
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/AutomatonSimulator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorSecondPreventive.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/AutomatonPerimeterResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/CurativeWithSecondPraoResult.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/AutomatonPerimeterResultImplTest.java
  sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityResult.java
Labels: bug, PR: waiting-for-review

#1177 No longer allow preventive OnContingencyState Usage Rules
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/OnContingencyStateAdderImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/OnContingencyStateAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/utils/ExhaustiveCracCreation.java
  data/crac/crac-io/crac-io-json/src/main/resources/schemas/on-contingency-state-usage-rule/on-contingency-state-usage-rule-v1.6.json
  data/crac/crac-io/crac-io-json/src/main/resources/schemas/on-contingency-state-usage-rule/on-contingency-state-usage-rule-v2.0.json
  data/crac/crac-io/crac-io-json/src/main/resources/schemas/on-state-usage-rule/on-state-usage-rule-v1.0.json
  data/crac/crac-io/crac-io-json/src/test/java/com/powsybl/openrao/data/crac/io/json/CracImportExportTest.java
  data/rao-result/rao-result-io/rao-result-json/src/test/resources/retrocompatibility/v1.1/crac-for-rao-result-v1.1.json
  data/rao-result/rao-result-io/rao-result-json/src/test/resources/retrocompatibility/v1.2/crac-for-rao-result-v1.2.json
  data/rao-result/rao-result-io/rao-result-json/src/test/resources/retrocompatibility/v1.3/crac-for-rao-result-v1.3.json
  data/rao-result/rao-result-io/rao-result-json/src/test/resources/retrocompatibility/v1.4/crac-for-rao-result-v1.4.json
  data/rao-result/rao-result-io/rao-result-json/src/test/resources/retrocompatibility/v1.5/crac-for-rao-result-v1.5.json
  data/rao-result/rao-result-io/rao-result-json/src/test/resources/retrocompatibility/v1.6/crac-for-rao-result-v1.6.json
Labels: PR: waiting-for-review, cleaning, breaking-change

#1206 Remove useless GLSK file
  data/glsk/glsk-document-cse/src/test/resources/testGlskHybrid.xml
Labels: cleaning

#1205 Use upward and downward variation variables in MILP for Range Actions
  docs/castor/linear-problem/core-problem-filler.md
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/LinearProblemTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
Labels: PR: waiting-for-review, cleaning, MIP

#1228 Temporal data
  commons/src/main/java/com/powsybl/openrao/commons/TemporalData.java
  commons/src/main/java/com/powsybl/openrao/commons/TemporalDataImpl.java
  commons/src/test/java/com/powsybl/openrao/commons/TemporalDataImplTest.java
Labels: feature, intertemporality

#1232 create class InterTemporalRaoInput
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/InterTemporalRaoInput.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/InterTemporalRaoInputTest.java
Labels: feature, PR: waiting-for-review, intertemporality

#1229 Power Gradient Constraint
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/crac/api/rangeaction/PstRangeActionAdder.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/crac/api/rangeaction/RangeAction.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/crac/api/rangeaction/StandardRangeActionAdder.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/crac/api/rangeaction/VariationDirection.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/AbstractRangeAction.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/AbstractStandardRangeActionAdder.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/CounterTradeRangeActionImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/HvdcRangeActionImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/InjectionRangeActionImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/PstRangeActionAdderImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/PstRangeActionImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/CounterTradeRangeActionAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/HvdcRangeActionAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/InjectionRangeActionAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/PstRangeActionAdderImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/utils/ExhaustiveCracCreation.java
  data/crac/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/crac/io/json/JsonSerializationConstants.java
  data/crac/crac-io/crac-io-json/src/test/java/com/powsybl/openrao/data/crac/io/json/JsonRetrocompatibilityTest.java
  data/inter-temporal-constraint/pom.xml
  data/inter-temporal-constraint/src/main/java/com/powsybl/openrao/data/intertemporalconstraint/PowerGradientConstraint.java
  data/inter-temporal-constraint/src/test/java/com/powsybl/openrao/data/intertemporalconstraint/PowerGradientConstraintTest.java
  data/pom.xml
  distribution/pom.xml
  docs/input-data/crac/json.md
  ra-optimisation/rao-api/pom.xml
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/InterTemporalRaoInput.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/InterTemporalRaoInputTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/RemedialActionCostEvaluator.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/RemedialActionCostEvaluatorImplTest.java
Labels: feature, PR: waiting-for-review, intertemporality

#1236 inter-tempoal RAO API
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/InterTemporalRao.java
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/InterTemporalRaoProvider.java
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/Rao.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/InterTemporalRaoTest.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/raomock/AnotherInterTemporalRaoProviderMock.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/raomock/InterTemporalRaoProviderMock.java
Labels: feature, PR: waiting-for-review, intertemporality

#1246 Classes generated by Jakarta implement interfaces
  data/crac/crac-io/crac-io-cim/pom.xml
  data/crac/crac-io/crac-io-csa-profiles/pom.xml
  data/crac/crac-io/crac-io-cse/pom.xml
  data/crac/crac-io/crac-io-fb-constraint/pom.xml
  data/rao-result/rao-result-io/rao-result-cne/cne-exporter-commons/pom.xml
  data/rao-result/rao-result-io/rao-result-cne/core-cne-exporter/pom.xml
  data/rao-result/rao-result-io/rao-result-cne/swe-cne-exporter/pom.xml
  data/refprog/refprog-xml-importer/pom.xml
Labels: bug, feature, dependencies, PR: waiting-for-review

#1087 Add new method withNetworkElement for InjectionRangeActionAdder
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/crac/api/rangeaction/InjectionRangeActionAdder.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/InjectionRangeActionAdderImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/InjectionRangeActionAdderImplTest.java
Labels: PR: waiting-for-info-reviewer, next-release

#1251 TemporalData::map
  commons/src/main/java/com/powsybl/openrao/commons/TemporalData.java
  commons/src/main/java/com/powsybl/openrao/commons/TemporalDataImpl.java
  commons/src/test/java/com/powsybl/openrao/commons/TemporalDataImplTest.java
Labels: feature, PR: waiting-for-review, intertemporality
