Repository powsybl/powsybl-open-rao, pull requests merged in 2025-02, with the labels that each got.

#1266 Fix format of datetimes in variable and constraint names
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
Labels: bug, intertemporality

#1256 Partial Failure and completeData
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorContingencyScenarios.java
  sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityAdapter.java
  sensitivity-analysis/src/main/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityResult.java
  sensitivity-analysis/src/test/java/com/powsybl/openrao/sensitivityanalysis/SystematicSensitivityResultTest.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic12_export_improvement/US12_15.feature
Labels: PR: waiting-for-review

#1265 Feature/timestamp in crac api
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/crac/api/Crac.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/crac/api/CracFactory.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/crac/api/State.java
  data/crac/crac-api/src/test/java/com/powsybl/openrao/data/crac/api/MockCrac.java
  data/crac/crac-api/src/test/java/com/powsybl/openrao/data/crac/api/MockCracFactory1.java
  data/crac/crac-api/src/test/java/com/powsybl/openrao/data/crac/api/MockCracFactory2.java
  data/crac/crac-api/src/test/java/com/powsybl/openrao/data/crac/api/MockState.java
  data/crac/crac-api/src/test/java/com/powsybl/openrao/data/crac/api/StateTest.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/CracImpl.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/CracImplFactory.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/PostContingencyState.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/PreventiveState.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/StateIdHelper.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/OnContingencyStateImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/OnFlowConstraintInCountryImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/PostContingencyStateTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/PreventiveStateTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/StateIdHelperTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/utils/ExhaustiveCracCreation.java
  data/crac/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/crac/io/json/JsonSerializationConstants.java
  data/crac/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/crac/io/json/deserializers/CracDeserializer.java
  data/crac/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/crac/io/json/serializers/CracSerializer.java
  data/crac/crac-io/crac-io-json/src/main/resources/schemas/crac/crac-v2.7.json
  data/crac/crac-io/crac-io-json/src/test/java/com/powsybl/openrao/data/crac/io/json/CracImportExportTest.java
  data/crac/crac-io/crac-io-json/src/test/java/com/powsybl/openrao/data/crac/io/json/JsonRetrocompatibilityTest.java
  data/crac/crac-io/crac-io-json/src/test/resources/emptyCrac.json
  data/crac/crac-io/crac-io-json/src/test/resources/retrocompatibility/v2/crac-v2.7.json
Labels: feature, new-crac-version

#1258 Inter-Temporal Skeleton (MARMOT)
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/NetworkActionImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/NetworkActionImplTest.java
  data/rao-result/rao-result-io/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresult/io/json/deserializers/ComputationStatusMapDeserializer.java
  data/rao-result/rao-result-io/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresult/io/json/serializers/ComputationStatusMapSerializer.java
  ra-optimisation/search-tree-rao/pom.xml
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/AutomatonSimulator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/Castor.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorContingencyScenarios.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorOneStateOnly.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorSecondPreventive.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/objectivefunction/ObjectiveFunctionCreator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizer.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/ProblemFillerHelper.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/AbstractCoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CostCoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/PowerGradientConstraintFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemBuilder.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/InterTemporalIteratingLinearOptimizer.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/InterTemporalIteratingLinearOptimizerInput.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/Marmot.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/MarmotUtils.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/PostOptimizationResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/TopologicalOptimizationResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalFlowResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalLinearOptimizationResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalRangeActionActivationResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalRemedialActionActivationResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalSensitivityResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/LinearProblemResult.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/LinearProblemBuilderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/PowerGradientConstraintFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/MarmotTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/MarmotUtilsTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/PostOptimizationResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/TestsUtils.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/TopologicalOptimizationResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalFlowResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalLinearOptimizationResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalRangeActionActivationResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalSensitivityResultTest.java
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-20250213.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-20250214.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-redispatching-202502141040.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-redispatching-202502141140.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-redispatching-202502141240.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-topo-202502181007.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-topo-202502191007.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/small-crac-2pst-1600.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/small-crac-2pst-1700.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/small-crac-2pst-1800.json
  ra-optimisation/search-tree-rao/src/test/resources/network/12Nodes_2_pst.uct
  ra-optimisation/search-tree-rao/src/test/resources/network/2Nodes2ParallelLinesPST.uct
  ra-optimisation/search-tree-rao/src/test/resources/network/2Nodes3ParallelLinesPST2LinesClosed.uct
  ra-optimisation/search-tree-rao/src/test/resources/network/3Nodes.uct
  ra-optimisation/search-tree-rao/src/test/resources/parameters/RaoParameters_dc_minObjective_discretePst.json
  ra-optimisation/search-tree-rao/src/test/resources/parameters/RaoParameters_minCost_megawatt_dc.json
Labels: feature, intertemporality
