Repository powsybl/powsybl-open-rao, pull requests merged in 2025-04, with the labels that each got.

#1345 All optional attributes in GeneratorConstraints
  data/generator-constraints/src/main/java/com/powsybl/openrao/data/generatorconstraints/GeneratorConstraints.java
  data/generator-constraints/src/test/java/com/powsybl/openrao/data/generatorconstraints/GeneratorConstraintsTest.java
Labels: cleaning

#1347 No longer export flows for instants after CNEC's
  data/rao-result/rao-result-io/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresult/io/json/serializers/FlowCnecResultArraySerializer.java
  data/rao-result/rao-result-io/rao-result-json/src/test/resources/rao-result.json
Labels: PR: waiting-for-review, cleaning, json, rao-result

#1353 Extract features from idcc test data
  commons/src/main/java/com/powsybl/openrao/commons/TemporalDataImpl.java
  data/crac/crac-io/crac-io-fb-constraint/src/main/java/com/powsybl/openrao/data/crac/io/fbconstraint/FbConstraintCracCreator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/optimizationperimeters/AbstractOptimizationPerimeter.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/RangeActionActivationResultImpl.java
Labels: PR: waiting-for-review

#1356 Remove unused flowbased-related modules
  data/flowbased-domain/pom.xml
  data/flowbased-domain/src/main/java/com/powsybl/openrao/data/flowbaseddomain/DataDomain.java
  data/flowbased-domain/src/main/java/com/powsybl/openrao/data/flowbaseddomain/DataGlskFactors.java
  data/flowbased-domain/src/main/java/com/powsybl/openrao/data/flowbaseddomain/DataMonitoredBranch.java
  data/flowbased-domain/src/main/java/com/powsybl/openrao/data/flowbaseddomain/DataPostContingency.java
  data/flowbased-domain/src/main/java/com/powsybl/openrao/data/flowbaseddomain/DataPreContingency.java
  data/flowbased-domain/src/main/java/com/powsybl/openrao/data/flowbaseddomain/DataPtdfPerCountry.java
  data/flowbased-domain/src/main/java/com/powsybl/openrao/data/flowbaseddomain/json/JsonFlowbasedDomain.java
  data/flowbased-domain/src/test/java/com/powsybl/openrao/data/flowbaseddomain/json/JsonFlowbasedDomainTest.java
  data/flowbased-domain/src/test/resources/dataDomain.json
  data/flowbased-domain/src/test/resources/logback-test.xml
  data/pom.xml
  distribution/pom.xml
  flowbased-computation/flowbased-computation-api/pom.xml
  flowbased-computation/flowbased-computation-api/src/main/java/com/powsybl/openrao/flowbasedcomputation/FlowbasedComputation.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/powsybl/openrao/flowbasedcomputation/FlowbasedComputationParameters.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/powsybl/openrao/flowbasedcomputation/FlowbasedComputationProvider.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/powsybl/openrao/flowbasedcomputation/FlowbasedComputationResult.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/powsybl/openrao/flowbasedcomputation/FlowbasedComputationResultImpl.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/powsybl/openrao/flowbasedcomputation/json/FlowbasedComputationParametersDeserializer.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/powsybl/openrao/flowbasedcomputation/json/FlowbasedComputationParametersJsonModule.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/powsybl/openrao/flowbasedcomputation/json/FlowbasedComputationParametersSerializer.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/powsybl/openrao/flowbasedcomputation/json/JsonFlowbasedComputationParameters.java
  flowbased-computation/flowbased-computation-api/src/main/java/com/powsybl/openrao/flowbasedcomputation/json/JsonFlowbasedComputationResult.java
  flowbased-computation/flowbased-computation-api/src/test/java/com/powsybl/openrao/flowbasedcomputation/FlowbasedComputationParametersTest.java
  flowbased-computation/flowbased-computation-api/src/test/java/com/powsybl/openrao/flowbasedcomputation/FlowbasedComputationProviderMock.java
  flowbased-computation/flowbased-computation-api/src/test/java/com/powsybl/openrao/flowbasedcomputation/FlowbasedComputationTest.java
  flowbased-computation/flowbased-computation-api/src/test/java/com/powsybl/openrao/flowbasedcomputation/NetworkUtil.java
  flowbased-computation/flowbased-computation-api/src/test/java/com/powsybl/openrao/flowbasedcomputation/json/JsonFlowbasedComputationParametersTest.java
  flowbased-computation/flowbased-computation-api/src/test/java/com/powsybl/openrao/flowbasedcomputation/json/JsonFlowbasedComputationResultTest.java
  flowbased-computation/flowbased-computation-api/src/test/resources/FlowbasedComputationParameters.json
  flowbased-computation/flowbased-computation-api/src/test/resources/FlowbasedComputationResult.json
  flowbased-computation/flowbased-computation-api/src/test/resources/fakeCrac.json
  flowbased-computation/flowbased-computation-api/src/test/resources/logback-test.xml
  flowbased-computation/flowbased-computation-api/src/test/resources/outputflowbased
  flowbased-computation/flowbased-computation-api/src/test/resources/testCase.xiidm
  flowbased-computation/flowbased-computation-impl/pom.xml
  flowbased-computation/flowbased-computation-impl/src/main/java/com/powsybl/openrao/flowbasedcomputation/impl/FlowbasedComputationImpl.java
  flowbased-computation/flowbased-computation-impl/src/test/java/com/powsybl/openrao/flowbasedcomputation/impl/ExampleGenerator.java
  flowbased-computation/flowbased-computation-impl/src/test/java/com/powsybl/openrao/flowbasedcomputation/impl/FlowbasedComputationImplTest.java
  flowbased-computation/flowbased-computation-impl/src/test/java/com/powsybl/openrao/flowbasedcomputation/impl/SensitivityComputationFactoryMock.java
  flowbased-computation/flowbased-computation-impl/src/test/resources/com/powsybl/config/test/config.yml
  flowbased-computation/flowbased-computation-impl/src/test/resources/com/powsybl/config/test/filelist.txt
  flowbased-computation/flowbased-computation-impl/src/test/resources/crac.json
  flowbased-computation/flowbased-computation-impl/src/test/resources/crac_for_rao_result.json
  flowbased-computation/flowbased-computation-impl/src/test/resources/crac_with_extension.json
  flowbased-computation/flowbased-computation-impl/src/test/resources/crac_with_forced.json
  flowbased-computation/flowbased-computation-impl/src/test/resources/logback-test.xml
  flowbased-computation/pom.xml
  pom.xml
  tests/pom.xml
  tests/src/test/java/com/powsybl/openrao/tests/steps/FlowbasedComputationSteps.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/flowbased_computation/flowbased.feature
Labels: PR: waiting-for-review, cleaning
