Repository powsybl/powsybl-open-rao, pull requests merged in 2025-01, with the labels that each got.

#1131 1129 use powsybl core method hasimpactonnetwork
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/NetworkActionImpl.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/DanglingLineActionImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/GeneratorActionImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/LoadActionImplTest.java
  data/crac/crac-impl/src/test/java/com/powsybl/openrao/data/crac/impl/ShuntCompensatorPositionActionImplTest.java
Labels: PR: waiting-for-review

#1259 Timestamp in variables and constraints
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemBuilder.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/LinearProblemResult.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/LinearProblemTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFillerMarginDecreaseRuleTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/LinearProblemResultTest.java
Labels: feature, MIP, intertemporality

#1250 Global balancing constraint
  docs/castor/linear-problem/core-problem-filler.md
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic93_redispatching/US93_1.feature
  tests/src/test/resources/files/cases/epic93/3Nodes.uct
  tests/src/test/resources/files/crac/epic93/crac-93-1-1.json
  tests/src/test/resources/files/crac/epic93/crac-93-1-2.json
  tests/src/test/resources/files/crac/epic93/crac-93-1-3.json
Labels: feature, PR: waiting-for-review, MIP

#1243 Costly optimization of range actions
  docs/castor/linear-problem/core-problem-filler.md
  docs/castor/linear-problem/discrete-pst-tap-filler.md
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorSecondPreventive.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/BestTapFinder.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/AbstractCoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CostCoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MarginCoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemBuilder.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/functionalcostcomputer/AbstractFunctionalCostComputer.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/functionalcostcomputer/MaximumFunctionalCostComputer.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/functionalcostcomputer/TotalFunctionalCostComputer.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/CurativeWithSecondPraoResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/LinearProblemResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/LinearProblemBuilderTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CostCoreProblemFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MarginCoreProblemFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxLoopFlowFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MnecFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/UnoptimizedCnecFillerMarginDecreaseRuleTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/functionalcostcomputer/FunctionalCostComputerTestUtils.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/functionalcostcomputer/MaximumFunctionalCostComputerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/functionalcostcomputer/TotalFunctionalCostComputerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/CurativeWithSecondPraoResultTest.java
  ra-optimisation/search-tree-rao/src/test/resources/crac/small-crac.json
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic92_costly_rao/US92_2.feature
  tests/src/test/resources/com/powsybl/openrao/tests/features/epic92_costly_rao/US92_3.feature
  tests/src/test/resources/files/cases/epic92/2Nodes2ParallelLinesPST.uct
  tests/src/test/resources/files/cases/epic92/2Nodes3ParallelLines2PSTs.uct
  tests/src/test/resources/files/cases/epic92/2Nodes3ParallelLinesPST.uct
  tests/src/test/resources/files/cases/epic92/2Nodes3ParallelLinesPST2LinesClosed.uct
  tests/src/test/resources/files/cases/epic92/2Nodes4ParallelLinesPST3LinesClosed.uct
  tests/src/test/resources/files/cases/epic92/2Nodes5ParallelLinesPST4LinesClosed.uct
  tests/src/test/resources/files/configurations/epic92/RaoParameters_dc_minObjective_2P.json
  tests/src/test/resources/files/configurations/epic92/RaoParameters_dc_minObjective_discretePst.json
  tests/src/test/resources/files/configurations/epic92/RaoParameters_dc_minObjective_discretePst_2P.json
  tests/src/test/resources/files/crac/epic92/crac-92-2-1.json
  tests/src/test/resources/files/crac/epic92/crac-92-2-2.json
  tests/src/test/resources/files/crac/epic92/crac-92-2-3.json
  tests/src/test/resources/files/crac/epic92/crac-92-2-4.json
  tests/src/test/resources/files/crac/epic92/crac-92-3-1.json
  tests/src/test/resources/files/crac/epic92/crac-92-3-2.json
  tests/src/test/resources/files/crac/epic92/crac-92-3-4.json
Labels: feature, PR: waiting-for-review, MIP

#1249 Angle monitoring noglsk
  monitoring/src/main/java/com/powsybl/openrao/monitoring/Monitoring.java
  monitoring/src/main/java/com/powsybl/openrao/monitoring/results/MonitoringResult.java
  monitoring/src/test/java/com/powsybl/openrao/monitoring/AngleMonitoringTest.java
Labels: PR: waiting-for-review

#1235 Inter-Temporal Pool
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/InterTemporalRaoInput.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/InterTemporalRaoInputTest.java
  util/src/main/java/com/powsybl/openrao/util/InterTemporalPool.java
  util/src/test/java/com/powsybl/openrao/util/InterTemporalPoolTest.java
Labels: feature, PR: waiting-for-correction, intertemporality

#1257 Power Gradient Constraint filler
  data/inter-temporal-constraint/src/main/java/com/powsybl/openrao/data/intertemporalconstraint/PowerGradient.java
  data/inter-temporal-constraint/src/main/java/com/powsybl/openrao/data/intertemporalconstraint/PowerGradientConstraint.java
  data/inter-temporal-constraint/src/test/java/com/powsybl/openrao/data/intertemporalconstraint/PowerGradientConstraintTest.java
  data/inter-temporal-constraint/src/test/java/com/powsybl/openrao/data/intertemporalconstraint/PowerGradientTest.java
  docs/castor/linear-problem.md
  docs/castor/linear-problem/power-gradient-constraint-filler.md
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/InterTemporalRaoInput.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/InterTemporalRaoInputTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/PowerGradientConstraintFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/PowerGradientConstraintFillerTest.java
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-1600.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-1700.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-1900.json
  ra-optimisation/search-tree-rao/src/test/resources/network/4Nodes.uct
Labels: feature, PR: waiting-for-correction, cleaning, MIP, intertemporality
