Repository powsybl/powsybl-open-rao, pull requests merged in 2025-03, with the labels that each got.

#1284 Remove timestamp in variables name for which a state is already provided
  commons/src/test/java/com/powsybl/openrao/commons/AbstractToolTest.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/crac/api/usagerule/OnConstraint.java
  data/crac/crac-api/src/main/java/com/powsybl/openrao/data/crac/api/usagerule/OnConstraintAdder.java
  data/crac/crac-impl/src/main/java/com/powsybl/openrao/data/crac/impl/OnConstraintAdderImpl.java
  data/crac/crac-io/crac-io-csa-profiles/src/main/java/com/powsybl/openrao/data/crac/io/csaprofiles/craccreator/remedialaction/AssociationStatus.java
  data/crac/crac-io/crac-io-csa-profiles/src/main/java/com/powsybl/openrao/data/crac/io/csaprofiles/craccreator/remedialaction/OnConstraintUsageRuleHelper.java
  data/crac/crac-io/crac-io-csa-profiles/src/main/java/com/powsybl/openrao/data/crac/io/csaprofiles/craccreator/remedialaction/OnContingencyStateUsageRuleHelper.java
  data/crac/crac-io/crac-io-csa-profiles/src/test/java/com/powsybl/openrao/data/crac/io/csaprofiles/craccreator/CsaProfileSsiTest.java
  data/crac/crac-io/crac-io-csa-profiles/src/test/java/com/powsybl/openrao/data/crac/io/csaprofiles/craccreator/NcAggregatorTest.java
  data/crac/crac-io/crac-io-csa-profiles/src/test/java/com/powsybl/openrao/data/crac/io/csaprofiles/craccreator/remedialaction/OnConstraintUsageRuleHelperTest.java
  data/crac/crac-io/crac-io-csa-profiles/src/test/java/com/powsybl/openrao/data/crac/io/csaprofiles/craccreator/remedialaction/OnContingencyStateUsageRuleHelperTest.java
  data/crac/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/crac/io/json/deserializers/OnConstraintArrayDeserializer.java
  data/crac/crac-io/crac-io-json/src/main/java/com/powsybl/openrao/data/crac/io/json/serializers/OnConstraintSerializer.java
  flowbased-computation/flowbased-computation-api/src/test/java/com/powsybl/openrao/flowbasedcomputation/FlowbasedComputationProviderMock.java
  flowbased-computation/flowbased-computation-api/src/test/java/com/powsybl/openrao/flowbasedcomputation/FlowbasedComputationTest.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/RaoTest.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/raomock/AnotherRaoProviderMock.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/raomock/RaoProviderMock.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/AbstractCoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CostCoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MarginCoreProblemFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/PowerGradientConstraintFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblem.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/linearproblem/LinearProblemIdGenerator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/LinearProblemResult.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/IteratingLinearOptimizerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/LinearProblemTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/ContinuousRangeActionGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/CostCoreProblemFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstGroupFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/DiscretePstTapFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MarginCoreProblemFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/MaxMinRelativeMarginFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/PowerGradientConstraintFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/RaUsageLimitsFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/LinearProblemResultTest.java
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-1600.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-1700.json
  ra-optimisation/search-tree-rao/src/test/resources/crac/crac-1900.json
Labels: cleaning, MIP

#1280 Priority ucte network analyser
  data/crac/crac-io/crac-io-commons/src/main/java/com/powsybl/openrao/data/crac/io/commons/ucte/UcteConnectable.java
  data/crac/crac-io/crac-io-commons/src/main/java/com/powsybl/openrao/data/crac/io/commons/ucte/UcteConnectableCollection.java
  data/crac/crac-io/crac-io-commons/src/main/java/com/powsybl/openrao/data/crac/io/commons/ucte/UcteNetworkAnalyzer.java
  data/crac/crac-io/crac-io-commons/src/main/java/com/powsybl/openrao/data/crac/io/commons/ucte/UcteNetworkAnalyzerProperties.java
  data/crac/crac-io/crac-io-commons/src/test/java/com/powsybl/openrao/data/crac/io/commons/ucte/UcteConnectableCollectionTest.java
  data/crac/crac-io/crac-io-commons/src/test/java/com/powsybl/openrao/data/crac/io/commons/ucte/UcteConnectableTest.java
  data/crac/crac-io/crac-io-commons/src/test/resources/TestCase_severalVoltageLevels_Xnodes_8characters_priority.uct
  data/crac/crac-io/crac-io-fb-constraint/src/main/java/com/powsybl/openrao/data/crac/io/fbconstraint/FbConstraintCracCreator.java
Labels: feature, PR: waiting-for-review

#1293 Generator constraints
  data/generator-constraints/pom.xml
  data/generator-constraints/src/main/java/com/powsybl/openrao/data/generatorconstraints/GeneratorConstraints.java
  data/generator-constraints/src/test/java/com/powsybl/openrao/data/generatorconstraints/GeneratorConstraintsTest.java
  data/inter-temporal-constraint/src/main/java/com/powsybl/openrao/data/intertemporalconstraint/PowerGradient.java
  data/pom.xml
  distribution/pom.xml
  pom.xml
Labels: feature, PR: waiting-for-review, intertemporality

#1282 [CIM] Import only one HVDC action if one line is disconnected
  data/crac/crac-io/crac-io-cim/src/main/java/com/powsybl/openrao/data/crac/io/cim/craccreator/HvdcRangeActionCreator.java
  data/crac/crac-io/crac-io-cim/src/main/java/com/powsybl/openrao/data/crac/io/cim/craccreator/RemedialActionSeriesCreator.java
  data/crac/crac-io/crac-io-cim/src/test/java/com/powsybl/openrao/data/crac/io/cim/craccreator/CimCracCreatorTest.java
  data/crac/crac-io/crac-io-cim/src/test/resources/cracs/CIM_with_HVDC.xml
  data/crac/crac-io/crac-io-cim/src/test/resources/cracs/CIM_with_HVDC_and_invalid_contingencies.xml
  data/crac/crac-io/crac-io-cim/src/test/resources/cracs/CIM_with_HVDC_error.xml
Labels: bug

#1295 Remove power gradients
  data/inter-temporal-constraint/pom.xml
  data/inter-temporal-constraint/src/main/java/com/powsybl/openrao/data/intertemporalconstraint/PowerGradient.java
  data/inter-temporal-constraint/src/test/java/com/powsybl/openrao/data/intertemporalconstraint/PowerGradientTest.java
  data/pom.xml
  distribution/pom.xml
  pom.xml
  ra-optimisation/rao-api/pom.xml
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/InterTemporalRaoInput.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/InterTemporalRaoInputTest.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/PowerGradientConstraintFiller.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/InterTemporalIteratingLinearOptimizer.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/InterTemporalIteratingLinearOptimizerInput.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/Marmot.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/linearoptimisation/algorithms/fillers/PowerGradientConstraintFillerTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/MarmotTest.java
Labels: PR: waiting-for-review, cleaning, intertemporality

#1303 Ignore duplicated CNECs in RAO status
  data/rao-result/rao-result-io/rao-result-json/src/main/java/com/powsybl/openrao/data/raoresult/io/json/serializers/FlowCnecResultArraySerializer.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorFullOptimization.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/castor/algorithm/CastorSecondPreventive.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/FlowCnecSorting.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/RaoLogger.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/RaoUtil.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/costevaluatorresult/AbsoluteCostEvaluatorResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/costevaluatorresult/AbstractStateWiseCostEvaluatorResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/costevaluatorresult/CostEvaluatorResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/costevaluatorresult/SumCnecWiseCostEvaluatorResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/costevaluatorresult/SumCostEvaluatorResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/costevaluatorresult/SumMaxPerTimestampCostEvaluatorResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/objectivefunction/ObjectiveFunctionResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/LoopFlowViolationCostEvaluator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/MinMarginEvaluator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/MinMarginViolationEvaluator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/MnecViolationCostEvaluator.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalLinearOptimizationResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/api/ObjectiveFunctionResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/AutomatonPerimeterResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/CurativeWithSecondPraoResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/IteratingLinearOptimizationResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/OneStateOnlyRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/OptimizationResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PrePerimeterSensitivityResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/PreventiveAndCurativesRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/result/impl/SkippedOptimizationResultImpl.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/searchtree/algorithms/Leaf.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/costevaluatorresult/AbsoluteCostEvaluatorResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/costevaluatorresult/SumCnecWiseCostEvaluatorResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/costevaluatorresult/SumCostEvaluatorResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/costevaluatorresult/SumMaxPerTimestampCostEvaluatorResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/LoopFlowViolationCostEvaluatorTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/MinMarginEvaluatorTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/MinMarginViolationEvaluatorTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/MnecViolationCostEvaluatorTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/RemedialActionCostEvaluatorImplTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/commons/objectivefunctionevaluator/SensitivityFailureOvercostEvaluatorTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/result/impl/OneStateOnlyRaoResultImplTest.java
Labels: feature, PR: waiting-for-correction

#1302 Separate global result from individual results per timestamp
  data/rao-result/rao-result-api/src/main/java/com/powsybl/openrao/data/raoresult/api/InterTemporalRaoResult.java
  data/rao-result/rao-result-api/src/main/java/com/powsybl/openrao/data/raoresult/api/RaoResult.java
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/InterTemporalRao.java
  ra-optimisation/rao-api/src/main/java/com/powsybl/openrao/raoapi/InterTemporalRaoProvider.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/InterTemporalRaoTest.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/raomock/AnotherInterTemporalRaoProviderMock.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/raomock/InterTemporalRaoProviderMock.java
  ra-optimisation/rao-api/src/test/java/com/powsybl/openrao/raoapi/raomock/InterTemporalRaoResultMock.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/InterTemporalIteratingLinearOptimizer.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/Marmot.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/MarmotUtils.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/PostOptimizationResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/AbstractGlobalResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalFlowResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalLinearOptimizationResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalRangeActionActivationResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/GlobalSensitivityResult.java
  ra-optimisation/search-tree-rao/src/main/java/com/powsybl/openrao/searchtreerao/marmot/results/InterTemporalRaoResultImpl.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/MarmotTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/MarmotUtilsTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/PostOptimizationResultTest.java
  ra-optimisation/search-tree-rao/src/test/java/com/powsybl/openrao/searchtreerao/marmot/results/InterTemporalRaoResultImplTest.java
Labels: bug, feature, PR: waiting-for-review, intertemporality

#1308 Fix RA import after invalid Contingency
  data/crac/crac-io/crac-io-cim/src/main/java/com/powsybl/openrao/data/crac/io/cim/craccreator/RemedialActionSeriesCreator.java
  data/crac/crac-io/crac-io-cim/src/test/java/com/powsybl/openrao/data/crac/io/cim/craccreator/CimCracCreatorTest.java
  data/crac/crac-io/crac-io-cim/src/test/resources/cracs/CIM_21_4_1.xml
Labels: bug, PR: waiting-for-review

#1309 Bump powsybl-core to 6.7.0, OLF to 1.15.0 and entsoe to 2.13.0
  pom.xml
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withExtensions.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withOLFParams.json
  ra-optimisation/rao-api/src/test/resources/RaoParameters_config_withPartialExtensions.json
Labels: breaking-change, Release 03/2025
